### ISSUE TITLE
kwm crashes when hovering over some windows

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#237] opened 2016-03-14 22:10 UTC
After cc737f02592e526b4eb06c1925b08f5266daf552 when hovering over a popup window (auto complete window) in Sublime Text 3, kwm crashes. 

On and before cc737f02592e526b4eb06c1925b08f5266daf552 kwm does not crash, but it does close the popup window when the mouse hovers over it. 

This used to not close the auto complete window, but i'm having trouble finding exactly when it broke. 

Ideally kwm would not close the sublime text 3 auto complete window, but at minimum it shouldn't crash kwm.

**Comment by koekeishiya** [comment] 2016-03-14 22:12
Bsp or monocle spaces?

If bsp space, is the node type bsp or monocle?

**Comment by chrishoage** [comment] 2016-03-14 22:13
BSP space with BSP node type.

**Comment by koekeishiya** [comment] 2016-03-14 22:46
A bit confused about the commits you linked, they are the same?

**Comment by chrishoage** [comment] 2016-03-14 22:47
They are, I'm saying after that commit it crashes, on and before that commit it closes the window but doesn't crash.

**Comment by koekeishiya** [comment] 2016-03-14 22:47
Will try and find something that I can reproduce with.

**Comment by koekeishiya** [comment] 2016-03-14 22:52
This bug makes no sense to me.
The commits I've done after the one you specified does not change anything related to behaviour for BSP-mode.

Could potentially be these changes from the PR?
https://github.com/koekeishiya/kwm/commit/9033ef4c3185f57853eb8be1f3234c857a753f5f

**Comment by chrishoage** [comment] 2016-03-14 22:53
Yeah, looking closer at the log it appears its the `kwm-overlay` changes that are causing the crash. Before the overlay PR the window closes, but doesn't crash.

**Comment by koekeishiya** [comment] 2016-03-14 22:57
Without having looked at the kwm-overlay code, it probably has something to do with it not being able to get the "AXUIElementRef" and it is used while NULL or something

**Comment by koekeishiya** [comment] 2016-03-14 23:06
Can you see if the following kwm-overlay fixes the problem?
https://gist.github.com/koekeishiya/74401b3b0ad6f7ef9e47

**Comment by chrishoage** [comment] 2016-03-14 23:08
It does indeed fix the crash! Still closes the window though.

**Comment by koekeishiya** [comment] 2016-03-14 23:10
Regarding kwm-overlay, I will probably rewrite all the parsing and window stuff in plain C, as we already have the Private.h file now.

Regarding the closing of the autocomplete-window, can you check the behaviour of this @ the commit before I did anything with the monocle-subtrees.

Uh, this commit: b8aad42461303cca18d270b14a2732edcb24c848

**Comment by chrishoage** [comment] 2016-03-14 23:19
I must be smoking something, because I can't find a commit where hovering over the window never closed the auto-complete window. 

I'll try and get more info around the window-closing issue in a few hours.

**Comment by chrishoage** [comment] 2016-03-14 23:29
So, it has to do with autorise. When I turn off autorise the window doesn't close. 

It's as if kwm is trying to give this window focus, which in turn removes focus from the main Sublime Text 3 window. This loss of focus causes ST3 to close the auto-complete window, and autoraise then focuses ST3 again. 

With this new insight I'm really not sure what could be done. Does kwm have knowledge if a window is spawned from another window? Does it have knowledge of it is focusable or not? 

If only there was some way to disable autoraise for these types of windows. I feel it might be able to cover Chrome Extension Windows. These auto-complete windows, probably a lot more sub-windows that aren't really windows. 

I fear that this may be tricky to impossible to solve due to the nature of autoraise.

**Comment by koekeishiya** [comment] 2016-03-14 23:30
This is potentially? caused by the change done here:
https://github.com/koekeishiya/kwm/issues/205

commit before the above issue was fixed:
6e3f77723b44daeac21121d1f11ff876fe5f4d05

**Comment by koekeishiya** [comment] 2016-03-14 23:32
> If only there was some way to disable autoraise for these types of windows. I feel it might be able to cover Chrome Extension Windows. These auto-complete windows, probably a lot more sub-windows that aren't really windows. 

I believe that these windows are not listed in the the window list returned by `AXUIElementCopyAttributeValues(appRef, kAXWindowsAttribute, 0, 100, &windowList)` but I have not confirmed this.

**Comment by chrishoage** [comment] 2016-03-14 23:35
> This is potentially? caused by the change done here:

No, that unfortunately does not appear to be it. The window is still closed when the mouse hovers over it. 

I think we might be able to close this issue for now, the real issue is now fixed (the crash) 

The other issue could probably be apart of a greater autorise issue that tracks Launchpad and similar issues with autorise.

**Closed** 2016-03-14 23:40 UTC

**Comment by koekeishiya** [comment] 2016-03-14 23:45
>> If only there was some way to disable autoraise for these types of windows. I feel it might be able to cover Chrome Extension Windows. These auto-complete windows, probably a lot more sub-windows that aren't really windows.

> I believe that these windows are not listed in the the window list returned by AXUIElementCopyAttributeValues(appRef, kAXWindowsAttribute, 0, 100, &windowList) but I have not confirmed this.

Just tested this, and the window list returned contains all these "windows that are not windows", and so this is not a solution we can use.
