### ISSUE TITLE
Using Launchpad and autofocus

### ISSUE THREAD

**Issue by gorjuspixels** [koekeishiya/kwm#16] opened 2015-12-22 20:26 UTC
While using autofocus feature, open launchpad and try selecting an app with your mouse. A window underneath gains focus, and the launchpad closes. I'm using two monitors, not sure if the issue exists with one monitor.

This issue exists only if you have two or more open windows in the space

**Comment by koekeishiya** [comment] 2015-12-22 20:34
The autofocus feature is kinda lacking and not working like I originally wanted it to.
The issue you describe happens with things such as "Spotlight" as well, while running autofocus.

I do not have any external monitors available atm, and I am unable to reproduce this bug with my current setup. This could very well be how multi-monitors are handled, and support for multiple monitors is very much in development still.

**Comment by blaxill** [comment] 2015-12-23 23:52
There is also an issue with contextual menus that overlay a different window. If the window does not own the context menu it will gain focus, closing the context menu.

**Comment by koekeishiya** [comment] 2015-12-23 23:57
I got a couple of ideas in mind that may solve the contextual issue. Definitely something I will look into when I have time.

**Comment by koekeishiya** [comment] 2015-12-26 21:16
The issue regarding contextual menus should now be solved.
Due to technical issues, if the menubar is visible, focus follows mouse will be ignored.

If you wish to use this feature enable autohide menu bar in El Capitan settings.
Regarding the autofocus problem, just create a new issue if you find that the problem persists.

**Closed by koekeishiya** 2015-12-26 21:16 UTC
Labels: bug
