### ISSUE TITLE
`a` key does not work when kwmc is active

### ISSUE THREAD

**Issue by aakashjog** [koekeishiya/kwm#253] opened 2016-03-22 07:19 UTC
Whenever kwmc is active, I am unable to write `a` anywhere. Interestingly however, `A` works perfectly fine.

The issue is not limited to a particular app, and happens everywhere.

If I quit kwmc using `kwmc quit`, I can write `a` again.

I am using OS X 10.11.3 El Capitan on an 13-inch MacBook Air.

**Comment by dominiklohmann** [comment] 2016-03-22 08:49
Duplicate of #243.

**Closed** 2016-03-22 12:35 UTC
