### ISSUE TITLE
No more borders

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#353] opened 2016-05-04 20:57 UTC
Hi,

Just updated to latest master version and updated my config file to reflect new api changes.

I move from
 
    kwmc config focused-border on 
    kwmc config focused-border size 3 
    kwmc config focused-border color 99FF0000 
    kwmc config focused-border radius 6 

to

    kwmc config border focused on 
    kwmc config border focused size 3 
    kwmc config border focused color 99FF0000 
    kwmc config border focused radius 6 

but no borders are displayed.

Any hints ?

Thanks,

**Comment by koekeishiya** [comment] 2016-05-04 21:41
Borders work just fine for me. Can you post a log of `stderr`?

**Comment by mickaelperrin** [comment] 2016-05-04 22:17
Here is the log starting kwm in iterm :

    Local Daemon is now running..
    ChangeSplitRatio() New Split-Ratio is 0.5
    Creating screen info for display ID: 69732928 Resolution: 1680x1050 Origin: (0,0)
    DisplayID 69732928 has index 0 and Identifier E5E926FF-FF83-8251-E163-D61F52FAA3E5
    CreateWindowNodeTree() Create Space 3

I tested it with this reduced config file:


    // Enable border for focused window
    kwmc config border focused on
    kwmc config border focused size 3
    kwmc config border focused color FFBDD322
    kwmc config border focused radius 6

    // Enable border for marked window
    kwmc config border marked on
    kwmc config border marked size 3
    kwmc config border marked color FFCC5577
    kwmc config border marked radius 6

BTW, how can I get a log starting kwm with LaunchAgent ? I looked in the console but got nothing and try to get one using `kwmc config reload 2&>1`. But got nothing.

**Comment by dominiklohmann** [comment] 2016-05-04 22:20
> BTW, how can I get a log starting kwm with LaunchAgent 


Add this to the `.plist` in `~/Library/LaunchAgents/`:
```
<key>StandardOutPath</key>
<string>/tmp/kwm.out</string>
<key>StandardErrorPath</key>
<string>/tmp/kwm.err</string>
```

You can then view stdout and stderr by doing either of these:
```
tail -f /tmp/kwm.out
tail -f /tmp/kwm.err
```

**Comment by koekeishiya** [comment] 2016-05-04 22:28
> I tested it with this reduced config file:

Still works just fine for me. Can you post your full config?

**Comment by mickaelperrin** [comment] 2016-05-04 22:32
Here is my [full configuration](https://gist.github.com/mickaelperrin/4988c79722363380a63bb34835e18400).

I got it working but using a totally crazy flow:

- restart kwm
- comment the line with the color command
- restart kwm

And now borders are displayed... but commented in the configuration file ?!?

**Comment by koekeishiya** [comment] 2016-05-04 22:40
So the problem is parsing `99ff0000`. I hate parsing so much..

**Comment by mickaelperrin** [comment] 2016-05-04 22:41
You're right, using the @dominiklohmann method, I got with my full configuration `Parse error: Unknown token 'FF0000'`.

BTW, @dominiklohmann thanks ;)

**Comment by koekeishiya** [comment] 2016-05-04 23:00
Fixed on master.

You need to prefix colors with `0x` to say that this should be parsed as a hexadecimal value.

```
kwmc config border focused on 
kwmc config border focused size 3 
kwmc config border focused color 0x99FF0000 
kwmc config border focused radius 6 
```

**Closed by koekeishiya** 2016-05-04 23:00 UTC

**Comment by koekeishiya** [comment] 2016-05-04 23:10
> I don't understand the format of the color scheme, the first two digit are for luminosity ? and three others for classic RGB ? 

The color format is ARGB (Alpha Red Green Blue) 32bits.
`0xffff0000` would be 255alpha, 255 red, 0 green, 0 blue etc.

**Comment by mickaelperrin** [comment] 2016-05-04 23:13
Awesome 👍
