### ISSUE TITLE
[master] Can i use single key as a bind?

### ISSUE THREAD

**Issue by ignatif** [koekeishiya/kwm#482] opened 2016-09-18 20:35 UTC
Hello. Can i use single key as a bind?

What I'm trying to do is set rshift as a bind to swap between Screens. So if I'm and Screen 1 and press rshift, i get focus of Screen 2 and same for Screen 2. Can you help me find a workaround for that?

**Comment by ignatif** [comment] 2016-09-18 20:42
Also when i change focus to another screen, I need to move mouse first to actually get focus of the screen.
So i can't changed focus to the screen with terminal and start typing instantly. I that case i would get focus back to the previous Screen.
Is there a way to fix this?

**Comment by matthewdias** [comment] 2016-09-18 20:44
for binding rshift, you can use something like [Karabiner](https://pqrs.org/osx/karabiner/) to remap it to a key, and then assign that key in kwm.

**Comment by koekeishiya** [comment] 2016-09-26 14:12
> Also when i change focus to another screen, I need to move mouse first to actually get focus of the screen.
So i can't changed focus to the screen with terminal and start typing instantly. In that case i would get focus back to the previous Screen.
Is there a way to fix this?

Unable to reproduce. Focusing another screen and typing instantly works just fine for me.

> Hello. Can i use single key as a bind?

> What I'm trying to do is set rshift as a bind to swap between Screens. So if I'm and Screen 1 and press rshift, i get focus of Screen 2 and same for Screen 2. Can you help me find a workaround for that?

Modifiers (cmd, shift etc) are handled separately from normal keys, by the system. Currently, this is not possible.

Might add this as a feature in [khd](https://github.com/koekeishiya/khd).
See #478 for upcoming changes to keybindings and Kwm.

**Comment by koekeishiya** [comment] 2016-09-27 14:27
Closing this due to reasons above. See https://github.com/koekeishiya/khd/issues/6 for any potential future updates.

**Closed by koekeishiya** 2016-09-27 14:27 UTC
Labels: question

**Comment by koekeishiya** [comment] 2016-09-28 15:09
After thinking a bit about this, I'm curious to how exactly this is supposed to work.

Say you bind `rshift` to do some command, then every time `rshift` is pressed the command is executed. To perform the command again, you have to release `rshift` and press it once more.

Now, say I also have a bind `rshift - p`. Then every time I would want to perform this command, it would first run the `rshift` command, because the modifier event is received (as a flag change), then the keypress `p` is received as a second event that uses the previous updated flags.

Is that working as intended?

Am I correct in assuming that modifiers used for modifier-only commands are not to be used in other bindings?
