### ISSUE TITLE
Confused by behavior

### ISSUE THREAD

**Issue by neverfox** [koekeishiya/kwm#275] opened 2016-03-29 02:22 UTC
Perhaps I'm merely misunderstanding how this is supposed to work, but after installing from homebrew (on El Capitan) and using the default `kwmrc`, the windows are constantly moving around on their own (seemingly based on how I move the mouse). Also some of the windows (particularly iTerm2) appear to "pulse". Is this normal?

**Comment by mcchabby** [comment] 2016-03-29 16:33
It's not. Try installing, or upgrading to, the newest version of Xcode. The issue is most likely caused by a missing Swift 2.2 library contained in the latest version of Xcode.

**Comment by neverfox** [comment] 2016-03-30 18:10
I just get by with XCode command line tools (so I don't have the full thing installed) and this is the homebrew binary of kwm. I guess it's possible that the kwm binary is behind the curve and needs a new build.

**Comment by dominiklohmann** [comment] 2016-03-30 18:12
You can find the example kwmrc of the 1.1.5 release on homebrew-binary here: https://github.com/koekeishiya/kwm/blob/v1.1.5/examples/kwmrc 

Keep in mind that master is quite a few changes ahead.

**Comment by koekeishiya** [comment] 2016-04-05 13:10
Any update on this? If not i'll close it

**Comment by Nickomang** [comment] 2016-04-06 01:30
I'm having the exact same issue on El Capitan. Updating XCode did not seem to fix anything.

**Comment by koekeishiya** [comment] 2016-04-06 01:44
This issue doesn't really tell me anything. I need more information to even start thinking about what could be causing this.

**Comment by Nickomang** [comment] 2016-04-06 01:47
Yeah, I realize it's not really much to go on, just thought I'd corroborate the existence of the bug. I'll try to do some more self-experimenting and get back to you. My inclination is that my nightly build of iTerm2 is the primary culprit, I have yet to try using kwm without an iTerm window in the mix, and the "pulsing" neverfox described has yet to happen with a window of another program.

**Comment by chrishoage** [comment] 2016-04-06 01:50
A screen capture of the issue would be a start?

**Comment by neverfox** [comment] 2016-04-06 01:58
Just to confirm, the full XCode is a dependency before even starting to consider that there's a real problem?

**Comment by chrishoage** [comment] 2016-04-06 02:01
Full XCode shouldn't be a dependency, but the XCode command line tools are.

**Comment by koekeishiya** [comment] 2016-04-06 14:53
In the latest release, the XCode command line tools should no longer be required.

**Comment by trifle** [comment] 2016-04-08 11:38
@koekeishiya This issue is most probably caused by #286. The binary on homebrew is 1.1.5 which crashes repeatedly. On re-starting, kwm will re-layout windows, causing the "pulsing" and switching symptoms. Affected users can easily confirm by looking at their syslog which should contain lines such as:

    08/04/16 13:31:22,114 com.apple.xpc.launchd[1]: (homebrew.mxcl.kwm[5134]) Service exited due to signal: Broken pipe: 13
    08/04/16 13:31:22,114 com.apple.xpc.launchd[1]: (homebrew.mxcl.kwm) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

If so, they can use the fixed kwm-overlay binary that is linked in #286.

**Comment by koekeishiya** [comment] 2016-04-08 15:46
Version 2.0.3 has been submitted to homebrew now.

**Closed by koekeishiya** 2016-04-08 15:46 UTC
