### ISSUE TITLE
Focus border doesn't jump to iTerm2 hotkey window

### ISSUE THREAD

**Issue by sxmichaels** [koekeishiya/kwm#363] opened 2016-05-11 03:29 UTC
I am using iTerm2's [hotkey window functionality](http://fokkezb.nl/2014/10/29/using-iterm2s-improved-visor/) on OSX 10.11.4 with kwm 2.2.0. I have set up an "iTerm2Visor" application, which is just iTerm2, but with a separate bundle name so that kwm can have a "float" rule for it. When I pop up the visor window with the hotkey, it becomes focused as expected, but the border stays on the previous window. Moving the mouse to the hotkey window resets the border to the right place; however, the border should have jumped there when the hotkey window first gained focus.

Screenshot below (the hotkey window displays across the top):
![](https://i.imgur.com/uyyz4nm.png)

**Comment by koekeishiya** [comment] 2016-05-11 17:26
duplicate of #299

**Closed by koekeishiya** 2016-05-11 17:26 UTC
Labels: duplicate

**Comment by sxmichaels** [comment] 2016-05-11 18:04
Ah, sorry, I had seen that bug report but didn't realize it was the same issue. In that case, for now, do you know if there is a way (via kwm or not) to toggle the focus border when a particular application gains/loses active state?

**Comment by koekeishiya** [comment] 2016-05-11 18:23
> In that case, for now, do you know if there is a way (via kwm or not) to toggle the focus border when a particular application gains/loses active state?

I do not think that is currently possible. You'd have to manually deactivate it using a bind.
