### ISSUE TITLE
4.0.3 from homebrew/folmulae fails codesigning on Mavericks

### ISSUE THREAD

**Issue by cdbzb** [koekeishiya/kwm#560] opened 2017-01-13 18:17 UTC
after upgrading kwm won't launch

1/13/17 10:15:34.366 AM tccd[341]: Unable to verify code signing identity of /usr/local/opt/kwm/kwm:  code failed to satisfy specified code requirement(s)

**Comment by koekeishiya** [comment] 2017-01-20 00:12
Not sure why that would be the cause, I only have El Capitan available for testing.
There is a new release on the homebrew repo, so I will close this issue

Feel free to create a new one if the problem persists for version 4.0.4.

Thanks.

**Closed by koekeishiya** 2017-01-20 00:12 UTC
