### ISSUE TITLE
request: Keybinding Cheatsheet Overlay

### ISSUE THREAD

**Issue by sebinsua** [koekeishiya/kwm#376] opened 2016-05-25 12:15 UTC
I found [this package for Atom](https://atom.io/packages/keybinding-cheatsheet) and wonder whether `kwm` could add a similar feature. 

It's difficult to memorise all of the keybindings before using this tool for the first time, and I think a feature to toggle a pane containing the currently assigned keybindings could help to ease new users into the program.

Perhaps `kwmc` could implement some command to export the current keybindings?

Thoughts?

**Comment by matthewdias** [comment] 2016-05-25 15:49
Due to the fact that you can assign whatever you want as keybinds (exec commands, etc), you might as well just open your config file as a reference. A cheatsheet panel would be really cluttered, and would just be a duplicate of what's in ur config anyway.

**Comment by chrishoage** [comment] 2016-05-25 17:56
I echo the "Just open your config" sentiment. kwm does not need any graphical interface (aside from the border)

**Comment by sebinsua** [comment] 2016-05-25 19:38
I'll see if I can implement it myself.

I'm thinking I could place my binds within a separate file referred to with `include binds` and then set up a `bindsym` that `exec`s a window that displays this `binds` file as well as replaces the `bindsym` with an `exec` that will close the window and then sets back the original `bindsym`. Unless there is a more elegant way of creating a toggle.

**Comment by matthewdias** [comment] 2016-05-25 19:43
you could use a binding mode to handle the replacing part.

**Closed** 2016-06-04 21:01 UTC

**Comment by koekeishiya** [comment] 2016-06-19 11:36
In case you still haven't found a proper solution to this, I would suggest just making a bind to open `~/.kwm/kwmrc` (or wherever your binds are), in your favorite text editor. There shouldn't really be a need for a toggle functionality, as you can just cmd+w/q that editor window when you are done.
