### ISSUE TITLE
macOS Sierra

### ISSUE THREAD

**Issue by mmmulani** [koekeishiya/kwm#383] opened 2016-06-16 19:08 UTC
I don

**Comment by mmmulani** [comment] 2016-06-16 19:09
agh, early submit.

I don't support anyone's tried kwm on Sierra yet? Opening this issue for any problems we encounter and to document work-arounds.

Also anyone else at WWDC?

**Comment by koekeishiya** [comment] 2016-06-16 19:18
I'll compile a list of private and deprecated API's I've been using, so that people can easily see if something has been removed.

**Comment by dominiklohmann** [comment] 2016-06-17 08:31
I've been using it in a VM for a while, if you want me to test something feel free to ask.

Kwm seems to be running just fine on 10.12.

**Comment by koekeishiya** [comment] 2016-06-17 14:00
> I've been using it in a VM for a while, if you want me to test something feel free to ask.

Can you test the pre-release of version 3.0.0 (current master branch) on 10.12 ?

**Comment by dominiklohmann** [comment] 2016-06-17 14:28
Been running it since a few minutes after you merged it in, the only thing that I cannot get to work after updating my config files is the custom rule for iTerm2 (neither `AXDialog` nor `AXApplication` work, it was the former in 10.11). 

I did not update my iTerm, this VM is an exact copy of my main drive updated to 10.12.

```
kwmc rule owner="iTerm2" properties={role="AXDialog"}
```

I also noticed that `Accessibility Inspector.app` is all new. Here's a screenshot of it inspecting iTerm2 borderless.

<img width="811" alt="screen shot 2016-06-17 at 16 24 35" src="https://cloud.githubusercontent.com/assets/4488655/16153814/4626662c-34a8-11e6-8492-9c690f8c65dc.png">

When I spawn a new iTerm2 window Kwm writes the following to stdout:

```
AXEvent_ApplicationLaunched: iTerm2
AXEvent_ApplicationActivated: iTerm2
```

**Comment by koekeishiya** [comment] 2016-06-17 14:35
Right, can confirm, should be fixed now.

**Comment by dominiklohmann** [comment] 2016-06-17 14:37
That fixed it. 👌

**Comment by dominiklohmann** [comment] 2016-06-17 14:43
I've found another issue with iTerm2. 

If I have any amount of iTerm2 windows open, restart Kwm, then open new iTerm2 windows, they get tiled as if the windows created before restarting Kwm weren't there. They never get tiled.

**Comment by koekeishiya** [comment] 2016-06-17 14:47
> If I have any amount of iTerm2 windows open, restart Kwm, then open new iTerm2 windows, they get tiled as if the windows created before restarting Kwm weren't there. They never get tiled.

Right, so what I believe is happening is that window rules only apply to windows that are created after Kwm was started. Not completely sure which approach to take for fixing this.

**Comment by dominiklohmann** [comment] 2016-06-17 14:50
Maybe window rules should get (re-)evaluated when a window gets added to the window tree? Not exactly sure how to tackle that issue, but it should probably get fixed.

**Comment by koekeishiya** [comment] 2016-06-17 14:54
Should be fixed in latest commit. Kwm will now reevaulate rules for all known windows, before creating the window-tree.

**Comment by dominiklohmann** [comment] 2016-06-17 14:59
Works flawlessly.

I now also get this warning for an unused function, probably some cleanup you can do.
```
kwm/window.cpp:423:1: warning: unused function 'GetAllAXWindowsNotInTree' [-Wunused-function]
GetAllAXWindowsNotInTree(ax_display *Display, std::vector<uint32_t> &WindowIDsInTree)
```

Sidenote: A word of warning, although that's probably a bug (I think?) with macOS: my self-signed codesign cert I used for Kwm did not transfer over when upgrading to 10.12. Make sure to safe your certificate so users that install via brew don't need to redo their Accessibility settings for Kwm.

**Comment by koekeishiya** [comment] 2016-06-17 15:22
> Sidenote: A word of warning, although that's probably a bug (I think?) with macOS: my self-signed codesign cert I used for Kwm did not transfer over when upgrading to 10.12. Make sure to safe your certificate so users that install via brew don't need to redo their Accessibility settings for Kwm.

I've exported it, however I am pretty sure I did not set the validity for more than 1 year, so it will expire 21dec 2016 I believe.

**Comment by matthewdias** [comment] 2016-06-17 20:30
Does it work okay with tabs? I would assume it does.

**Comment by dominiklohmann** [comment] 2016-06-18 00:38
> Does it work okay with tabs? I would assume it does.

If you mean with the new "collect windows in tabs" feature that is supposed to work seamlessly for every application (it kinda doesn't), yes, it does work with Kwm. It still only counts as a single window.

**Comment by dominiklohmann** [comment] 2016-06-18 13:26
Found another issue and I'm not sure if that's an issue with macOS Sierra or Kwm (current master).

When resizing the Safari window by switching between one and two or more open tabs, Safari only sometimes gets resized to the correct container size. You can see a screencast of the issue happening here: https://gfycat.com/ShimmeringDependableDuiker

**Comment by koekeishiya** [comment] 2016-06-18 13:41
> When resizing the Safari window by switching between one and two or more open tabs, Safari only sometimes gets resized to the correct container size.

Can reproduce. I believe the issue is that Safari sends multiple window_resized notifications, when Kwm receives the first one, it resizes it back and marks that event as intrinsic. I suspect that some of the actual notifications sent by safari gets mixed in and treated as intrinsic, which causes Kwm to ignore that event.

The reason for this system is so that Kwm can differentiate between events caused by an action it performed on a window, and external modifications.

**Comment by dominiklohmann** [comment] 2016-06-18 13:49
That might be an issue especially in 10.12 then, since all native applications gain Safari's tab feature by default ("window grouping").

**Comment by jhenahan** [comment] 2016-06-20 05:48
Just to let you know about some upcoming changes in Swift:

https://gist.github.com/jhenahan/7a353c9539d1bbea0a07a4152897f8de

That's the result when changing the SDK root in the makefile to point to the 10.12 SDK.

**Comment by koekeishiya** [comment] 2016-08-13 12:06
> When resizing the Safari window by switching between one and two or more open tabs, Safari only sometimes gets resized to the correct container size.

So this has actually been fixed in version 3.0.6.

**Comment by matthewdias** [comment] 2016-09-20 23:07
Creating new tabs is making it act like new windows are being opened. The window that I'm opening new tabs in gets smaller as if new windows are being tiled in next to it.

**Comment by koekeishiya** [comment] 2016-09-27 14:32
> Creating new tabs is making it act like new windows are being opened. The window that I'm opening new tabs in gets smaller as if new windows are being tiled in next to it.

This sounds like a tricky problem to solve.

I'll still be running 'El Capitan' for some time, so don't expect any work on this in the near future.

**Comment by dominiklohmann** [comment] 2016-09-27 17:21
> Creating new tabs is making it act like new windows are being opened. The window that I'm opening new tabs in gets smaller as if new windows are being tiled in next to it.

Funnily enough this used to work in the beta and I can't get it to work now either. I wonder how it behaves differently from Safari tabs now.

**Comment by koekeishiya** [comment] 2017-02-05 13:03
Closing this as Sierra support seems to be more or less ok.
Feel free to reopen a ticket regarding the tabbed window issue for tracking, if necessary.

**Closed by koekeishiya** 2017-02-05 13:03 UTC
Labels: question
