### ISSUE TITLE
[master] Move window between displays (Mission Control)

### ISSUE THREAD

**Issue by zo7** [koekeishiya/kwm#445] opened 2016-08-21 16:01 UTC
This is a somewhat difficult issue to debug and reproduce, but occasionally when I'm working with an external monitor windows from one space will switch to the space on the other monitor. It happens pretty randomly, but enough to be somewhat disruptive. Once all my windows are set for a while it seems to stabilize, which makes me wonder if there's a problem related to when the monitor is plugged in / removed or with moving windows between spaces.

This might be related to #330, and I'm also experiencing issues described in #401.

I'm using kwm 3.0.2 installed from Homebrew on El Capitan (10.11.6). The problem started occurring when I updated, previously when I was working with 2.x I didn't notice any problems.

Let me know if there's anything more I can do to help!

**Comment by koekeishiya** [comment] 2016-08-22 17:03
There have been a lot of issues that cause similar symptoms, and some of them has been fixed in version 3.0.7. Could you upgrade and use the newest version for some time, and then post an update whether or not your particular issue can be reproduced there as well?

**Comment by zo7** [comment] 2016-08-22 20:17
Will do, didn't realize I was so far behind. (I must've been using a different Homebrew repo than described in the readme...) So far so good but I'll update in a bit when I know for sure. Thanks!

**Comment by zo7** [comment] 2016-08-22 22:38
Yup, still happens occasionally on 3.0.7. One way I managed to reproduce it:

1. Have a window on the primary (laptop) monitor.
2. Move it to the external monitor (by bringing up Mission Control and dragging it over). It should automatically fill up the space. (If it doesn't or it experiences the "phantom windows" then try switching spaces on the new monitor until it snaps to fill the space, otherwise it won't work)
3. Open up a new window in the external monitor's space (e.g: by opening a new app with Spotlight). It should open to the right of the other window, otherwise it may not work.
4. Move the newly created window back to the primary monitor (again with Mission Control). It should be sitting to the side somewhat off the screen (presumably because it's trying to keep the position from the other monitor) and should **not** snap to fill up the space.
5. Change spaces a few times on the primary monitor. When you go back to the space you started on the window in the external monitor should snap to the primary monitor.

Other info:

* The external monitor is 1920x1080 at 1x resolution, while my laptop is a 1280x800 retina screen.
* Under "System Preferences -> Mission Control" I have "Displays have separate Spaces" ticked on.

My `kwmrc` is pretty simple:

    kwmc config tiling bsp
    kwmc config hotkeys on
    kwmc config padding 20 20 20 20
    kwmc config float-non-resizeable on

If you have any idea of what might be causing it (or if you could even point me to where I should look if I want to take a stab at fixing it) let me know.

**Comment by koekeishiya** [comment] 2016-08-24 09:00
> Move it to the external monitor (by bringing up Mission Control and dragging it over). It should automatically fill up the space.

Ideally, this would be true. However, there is no way for Kwm to know that a window was dragged using mission control as OSX does not send any notifications regardnig this, and it is therefore not supported. 

It used to work in 2.x.x versions because of a polling-based core rather than relying on notifictions as 3.x.x does.

**Comment by zo7** [comment] 2016-08-27 16:21
> Ideally, this would be true.

What I was describing was what actually happens though. I think because the mouse is over the window after I finished dragging the window is brought into focus, allowing kwm to do its thing.

I didn't know that there isn't a notification for that though, and I'm suspecting that my habit of using mission control to move windows across displays might be causing this issue. kwm does still seem to "know" that the window is on the correct display, however, but it still occasionally throws the window back on the other display for no apparent reason.

**Comment by koekeishiya** [comment] 2016-08-27 17:50
>  I think because the mouse is over the window after I finished dragging the window is brought into focus, allowing kwm to do its thing.

Kwm will sometimes be able to properly tile the window, yeah.

> I didn't know that there isn't a notification for that though, and I'm suspecting that my habit of using mission control to move windows across displays might be causing this issue. kwm does still seem to "know" that the window is on the correct display, however, but it still occasionally throws the window back on the other display for no apparent reason.

What I believe is happening, is that Kwm thinks the window is tiled on both displays (because there is no notification that says to untile it, when moved though mission control), causing what appears to be "randomly" moving the window back to that display.

**Comment by zo7** [comment] 2016-08-27 18:21
> What I believe is happening, is that Kwm thinks the window is tiled on both displays (because there is no notification that says to untile it, when moved through mission control), causing what appears to be "randomly" moving the window back to that display.

Ok, interesting. If that's the case, would it make sense to constrain each window to only allow tiling on one display? (so if it tries to tile the window on another display, make sure it untiles the old one?) I don't know what other side effects that might cause...

I'm totally willing to attempt to fix this myself btw, especially since I seem to be the only one experiencing this.

**Comment by koekeishiya** [comment] 2016-08-28 12:46
> Ok, interesting. If that's the case, would it make sense to constrain each window to only allow tiling on one display? (so if it tries to tile the window on another display, make sure it untiles the old one?) I don't know what other side effects that might cause...

This wouldn't necessarily cause any sideeffects, except for a potential performance toll.

A window has no notion of itself being tiled or not, so everytime you try to tile a window, you would essentially have to iterate through all connected displays and see if this window is tiled on the active space of that display, and if it is, untile it there.

If you are interested in trying that approach, you'd need to perform the following change to the function `AddWindowToNodeTree(..) in kwm/window.cpp:1006`

**Comment by zo7** [comment] 2016-08-28 14:45
Great, thanks for your help! I'll let you know if I make any progress.

**Comment by koekeishiya** [comment] 2017-01-10 19:50
This issue was actually fixed in version 4.0.2.

**Closed by koekeishiya** 2017-01-10 19:50 UTC
Labels: bug

**Comment by zo7** [comment] 2017-01-10 21:56
@koekeishiya Oh thanks! Sorry I never made much progress on this!
