### ISSUE TITLE
Crashing after monocle-trees update

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#234] opened 2016-03-13 20:25 UTC
After pulling the latest master (with `monocle-trees`) I am crashing quite a lot. There seem to be issues when I have my 2nd display in monocle mode with this update. 

Giving focus to the 2nd display while in monocle mode (at least, haven't tried both spaces in bsp) will very often crash kwm. 

Further more, when creating a monocle-tree while my 2nd display is in monocle mode it pulls ALL the other windows that were in monocle mode into the new monocle-tree 

Is it not possible to have a monocle-tree and a space in monocle mode?

**Comment by chrishoage** [comment] 2016-03-13 20:25
I had to downgrade to 5e43a3e759f116ed0ee7bad07b41911c9b17b7b7 the crashing was so severe

**Comment by dominiklohmann** [comment] 2016-03-13 20:29
It works just fine in a single monitor environment for me, but it really is unusable with multiple monitors for me as well. Thanks for the commit id to go back to, @chrishoage.

**Comment by koekeishiya** [comment] 2016-03-13 20:30
just a quick oversight on my part, forgot to update some of the code to match the changes in internal tree structure, sorry about that.

Will probably push later tonight.

**Comment by koekeishiya** [comment] 2016-03-13 22:00
Just to confirm, this only happens if any of the space is in monocle mode instead of bsp, right?

**Comment by chrishoage** [comment] 2016-03-13 22:02
I never tired BSP before I downgraded, but yes, this did happen when one space (my 2nd display) was in monocle mode.

**Comment by koekeishiya** [comment] 2016-03-13 22:04
> I never tired BSP before I downgraded, but yes, this did happen when one space (my 2nd display) was in monocle mode. 

Alright, I can only reproduce it with one of the spaces are in monocle mode.
I think I have found the reason for why it happens, looking into it at the moment.

**Comment by koekeishiya** [comment] 2016-03-13 22:59
Should be fixed.

Focus-wrapping is currently broken in monocle spaces. Will look into this in a bit.

**Closed** 2016-03-13 22:58 UTC

**Comment by koekeishiya** [comment] 2016-03-14 01:13
The focus should now wrap properly for monocle spaces, as before.
