### ISSUE TITLE
Window border is offset by left padding on launch of Kwm

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#318] opened 2016-04-17 16:57 UTC
When restarting Kwm, the window border is always at the very left of the screen, while all the other paddings work just fine. 

<img width="1440" alt="screen shot 2016-04-17 at 18 55 36" src="https://cloud.githubusercontent.com/assets/4488655/14588623/25247d24-04ce-11e6-9fd3-724bb04a4d74.png">

**Comment by matthewdias** [comment] 2016-04-18 02:12
I've noticed this happening randomly while using Sublime Text, not just when restarting. I think it might be caused by the completion overlays. It always happened when Sublime wasn't focused, and when i started typing in it, (allegedly due to the overlays?) the border would eventually move back to the proper position.

**Comment by cHoco** [comment] 2016-04-18 11:00
This happens (at least at startup) because just after `kwm-overlay` is started, `kwm` calls `ClearBorder` (sending "clear" command to kwm-overlay) than `RefreshBorder` (sending the command with the x,y,w,h and stroke colour, width, radius). 
But when these two commands are sent `kwm-overlay` hasn't finished starting and so isn't listening to its `stdin`. When it finally starts the two commands are viewed as one and because of how the command is parsed the x value isn't recognised thus defaulting to 0.

This can be fixed by either waiting for `kwm-overlay` to finish starting up when it's executed in `OpenBorder` or deal with multiple commands. Since @matthewdias has noticed the same issue in other situations maybe the second solution would be better.
Please try this diff and tell me if you notice any problems https://gist.github.com/cHoco/fbe96d1ada9bf50844e05bd2cd86d711/ra so I can submit a pull request :D

**Comment by dominiklohmann** [comment] 2016-04-18 14:28
Tried the diff, in that very same situation it leaves you without a border until you focus another window.

**Comment by cHoco** [comment] 2016-04-18 16:45
If you have the mouse cursor over a window when starting it isn't focused?

**Comment by dominiklohmann** [comment] 2016-04-18 16:47
It's focused, but it gets no border until I change focus in some way with the patch applied.

**Comment by cHoco** [comment] 2016-04-18 16:53
kwm doesn't *register* the currently focused app when starting up, so that may be the issue here.
Just to make sure can you try this patch and show the complete output when starting? thank you

**Comment by dominiklohmann** [comment] 2016-04-18 17:00
With my mouse over the window (border offset by left padding):

```
Local Daemon is now running..
ChangeSplitRatio() New Split-Ratio is 0.5
DisplayID 440939931 has index 0
DisplayID 440939932 has index 1
CreateWindowNodeTree() Create Space 861
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: dominiklohmann — tail — 263×67 55,35
```

With my mouse besides the window (no border):

```
Local Daemon is now running..
ChangeSplitRatio() New Split-Ratio is 0.5
DisplayID 440939931 has index 0
DisplayID 440939932 has index 1
CreateWindowNodeTree() Create Space 861
SetWindowDimensions() Update window dimensions
```

Sometimes Kwm hangs for a bit on startup and it takes a bit until "Local Daemon is now running..." appears in the log. In that case, I get no border even with the mouse over the window. I can not reproduce this consistently though.

**Comment by cHoco** [comment] 2016-04-18 17:09
Ok, that should be solvable by a call to `FocusWindowOfOSX` last patch I promise XD
https://gist.github.com/cHoco/df000ef6124e8218125d4fcbceb6584e/raw
Also please issue a make clean before rebuilding because some objects aren't rebuilt for some reasonn :/

**Comment by dominiklohmann** [comment] 2016-04-18 17:14
Works in both cases now:

```
Clear cmd
Refresh cmd
Quit cmd
Local Daemon is now running..
ChangeSplitRatio() New Split-Ratio is 0.5
DisplayID 440939931 has index 0
DisplayID 440939932 has index 1
There is an app
REFRESHING BORDER
CreateWindowNodeTree() Create Space 861
SetWindowDimensions() Update window dimensions
```

**Comment by matthewdias** [comment] 2016-04-18 17:29
Seems to have fixed my issue too.

**Closed** 2016-04-18 19:39 UTC

**Comment by matthewdias** [comment] 2016-04-19 01:16
now I'm getting this http://cl.ly/043R2V47292I
