### ISSUE TITLE
kwm-overlay border wrong frame calculation

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#198] opened 2016-02-29 16:15 UTC
I noticed that kwm-overlay doesn't always have the right frame size. You can easily notice it by resizing an application frame. Sometimes you'll see that the border frame doesn't match the application frame.
After some quick debugging I noticed that the method used to obtain window frame doesn't always return the correct value.

Possible fixes that I can think of:

1- modify FocusedAXObserverCallback to also handle the info parameter of the notification that should contain the new window size when app is resized and pass the value to kwm-overlay
2- modify kwm-overlay to use the AX family functions that in my tests seem to always return the correct value.

I haven't tested the first solution but it should work and it would probably be better/easier. I implemented a work in progress version of the second solution because I wanted to play around with swift and interact with the AX api :smile:  If anyone wants to test that branch https://github.com/cHoco/kwm/tree/parse_frame_ax

**Comment by koekeishiya** [comment] 2016-02-29 16:29
The window size is actually being retrieved from within the kwm-overlay application itself. Kwm just passes the window id.

The reason that it does not always update is that creation of notifications appear to fail once in a while, for no apparent reason.

**Comment by cHoco** [comment] 2016-02-29 16:34
Yeah but sometimes the notification is issued but the value computer by kwm-overlay isn't correct because CGWindowListCopyWindowInfo returns a dictionary with kCGWindowBounds not updated to latest notification, for some reason. That's what I was referring in this issue.

**Comment by koekeishiya** [comment] 2016-02-29 16:35
> Yeah but sometimes the notification is issued but the value computer by kwm-overlay isn't correct because CGWindowListCopyWindowInfo returns a dictionary with kCGWindowBounds not updated to latest notification

Do you have steps to reproduce? I've not come across this behavour.

**Comment by cHoco** [comment] 2016-02-29 16:40
I first noticed when using Tweetbot. When opening image windows and closing them the border would always have the wrong size (probably because the window opening and closing was animated)
I can reproduce it manually by resizing the focused window rapidly with the mouse.

**Comment by koekeishiya** [comment] 2016-02-29 16:45
Aight I can reproduce.

Although, if the solution requires kwm-overlay to have accessibility access, there is no need for Kwm to manage when it should be updated. It could simply just grab the focused window upon launch and register for its own events.

We would then have a "focused" and "marked" toggle, so that Kwm can still say what kind of border it wants to open.

**Comment by chrishoage** [comment] 2016-02-29 17:50
The overlay can take the size and position of the window as arguments too, if kwm can get more accurate data.

**Comment by koekeishiya** [comment] 2016-02-29 18:23
I tried the fix you've provided so far, and this does fix the issue, and I do not have to grant the kwm-overlay accessibliy access. This is probably due to it being managed by Kwm, although not completely sure why that worked.

However, the fix supplied assumes that the kwm-overlay should only surround the focused window of an application, and this does break support for marked window borders.

**Comment by cHoco** [comment] 2016-02-29 19:04
> However, the fix supplied assumes that the kwm-overlay should only surround the focused window of an application, and this does break support for marked window borders.

Yes, I should iterate over all window and select the one base on the window id, it was just a WIP.

Personally I'd like to try and test the other approach I mentioned (modify FocusedAXObserverCallback, use the info param and pass the values to kwm-overlay) first, since we would be replicating code if we look for the same notification both in kwm and kwm-overlay. On the other hand I noticed, as you pointed out in the first post, that some notifications aren't received by kwm. But using another program during my testing (https://github.com/puffnfresh/Honer.app) the same notification was received. Maybe decoupling notification from kwm would fix that issue aswell.

Honestly I don't know why It wouldn't require Accessibility permission.

**Comment by koekeishiya** [comment] 2016-02-29 19:13
> Honestly I don't know why It wouldn't require Accessibility permission.

I would assume this works because Kwm is the parent process of kwm-overlay, and it does have access.

**Comment by cHoco** [comment] 2016-03-02 19:07
Mmm I tested the first approach and the dictionary passed to the callback is empty every time :-1: 
so we got two choices, use AX apis in overlay program as I did in the other branch (should fix it up to make it work for other borders) or pass pass the frame to kwm-overlay and remove frame calculation code from it. Which approach would you prefer?

**Comment by koekeishiya** [comment] 2016-03-02 20:59
> Although, if the solution requires kwm-overlay to have accessibility access, there is no need for Kwm to manage when it should be updated. It could simply just grab the focused window upon launch and register for its own events.

> We would then have a "focused" and "marked" toggle, so that Kwm can still say what kind of border it wants to open.

I think this is the more appropriate solution. kwm-overlay would register for notifications, instead of Kwm.

**Comment by koekeishiya** [comment] 2016-03-10 23:47
> Mmm I tested the first approach and the dictionary passed to the callback is empty every time

This is happening because I pass `NULL` when creating the observer, see `CreateApplicationNotifications()` @ kwm/notifications.cpp

**Comment by cHoco** [comment] 2016-03-11 00:19
Do you mean when registering for a new notification? As I understood that value is passed directly to the callback as context data, and it shouldn't matter if we keep it null or not. 
Between here's the code I used when tried this out https://gist.github.com/a7e8c54a86d0fa9b6776

Between sorry for taking so long, I should submit the pull request for kwm-overlay with the new AX Api this weekend.

**Comment by koekeishiya** [comment] 2016-03-11 00:24
> Do you mean when registering for a new notification? As I understood that value is passed directly to the callback as context data, and it shouldn't matter if we keep it null or not.
Between here's the code I used when tried this out https://gist.github.com/a7e8c54a86d0fa9b6776

Oh, I had no idea there was such a thing as `AXObserverCreateWithInfoCallback`. Testing it just now, indeed it is empty. There is a built-in function you can use to display the content of CoreFoundation variables, called `CFShow` that you can use.

> Between sorry for taking so long, I should submit the pull request for kwm-overlay with the new AX Api this weekend.

That sounds great, cheers.

**Comment by koekeishiya** [comment] 2016-03-14 01:18
Fixed in pullrequest #235

**Closed by koekeishiya** 2016-03-14 01:18 UTC
