### ISSUE TITLE
config to emulate i3's workspace?

### ISSUE THREAD

**Issue by biocyberman** [koekeishiya/kwm#244] opened 2016-03-21 13:14 UTC
I am a i3wm user on Linux. This is my second day of trying `kwm`, and I am very happy to find `kwm` offer the best match to `i3wm` on Mac OS, most imporantly, the plain config file `kwmrc` (`.i3/config` equivalent). This lets me customize, backup, share easily. So the  mindset I have is to recreate the setup I have on `i3`. Sorry if this makes Mac OS sound inferior :D 

Well, one thing I have been trying is the 'workspace' handling, but not clear how to do it with `kwm`:

1. Switch/Open workspace and open default App (called space or desktop in Mac OS) shortcut key.  
For example: I want to jump to workspace and open default App for that workspace:
`kwmc bind f9+1 workspace 1:mail sys open -n Outlook`. Meaning: press F9+1 to move focus to workspace number 1, named `mail` and open Outlook if it is not running.

2. Default workspace for Apps. 
This is somewhat like `capture` but more flexible. Currently `kwmc config capture 2 iTunes` through iTunes to screen 1. But I am think of something like this:
`kwmc config default workspace 2:music iTunes`. Meaning to assign default workspace number 2, named music to iTunes. Then I can move iTunes to other workspace when needed.

Thanks
Vang

**Comment by koekeishiya** [comment] 2016-03-21 13:48
There are no APIs to deal with spaces on OSX, so the support is very limited. 

> Meaning: press F9+1 to move focus to workspace number 1, named mail and open Outlook if it is not running.

I don't think spaces in OSX can have user-set names, at least I have never seen that before.
The following bash script would move focus to space with id 1, and open mail if it is not running:
```
kwmc=/path/to/kwmc
$kwmc space -s id 1
open -n Outlook 
```
For this to work, you need to set `kwmc config spaces-key ..` to the modifiers OSX uses for "switch to workspace 'x'". Where 'x' should be the space id.
(Sys Pref -> Keyboard -> Shortcuts -> Mission Control)

> Default workspace for Apps.
This is somewhat like capture but more flexible. Currently kwmc config capture 2 iTunes through iTunes to screen 1. But I am think of something like this:
kwmc config default workspace 2:music iTunes. Meaning to assign default workspace number 2, named music to iTunes. Then I can move iTunes to other workspace when needed.

This might be possible to do, will look into it.

**Comment by matthewdias** [comment] 2016-03-21 19:56
>Default workspace for Apps.

You can do this natively in OS X by right-clicking an app in the dock and assigning it to the current desktop.

**Comment by biocyberman** [comment] 2016-03-21 21:09
@matthewdias I also read about the trick not long before posting the question. I can achieve the effect despite the misleading option texts: "Assign to Desktop on Display <n>", which seems I can only assign a default Monitor for an app. However, a line in kwmrc is still better for portability and re-usability reasons.

**Comment by koekeishiya** [comment] 2016-04-22 17:32
See #284 for `Assigning applications / windows to space 'x' on display 'y'`

**Closed by koekeishiya** 2016-04-22 17:32 UTC
Labels: question

**Comment by koekeishiya** [comment] 2016-04-23 15:20
Copy of post from the other issue.


This has been implemented on master.
Example rules:

Assign itunes to space 1 of display 1.
kwmc rule owner="iTunes" properties={space="1"; display="1"}

Assign itunes to space 1 of the primary display (display 0).
kwmc rule owner="iTunes" properties={space="1"}

Note: Windows with the space or display property set will automatically be moved back to that space / display if the user moves the window to another space / display, regardless of the method used. This is working as intended and will not be changed
