### ISSUE TITLE
Border not updated after floating window is moved.

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#147] opened 2016-02-04 22:01 UTC
Working in 3758f91a4331f05c7b4bac7ff1702b42be48241e
Stopped  working in affd1a2a78ddbbfdff4a09505afe7426c9c4ea5e

Hasn't worked since that commit. Checked quite a few of them.

**Comment by koekeishiya** [comment] 2016-02-04 22:01
Already fixed in a commit earlier today.

**Comment by chrishoage** [comment] 2016-02-04 22:03
Odd, it appears to only happen with System Preferences. 

Perhaps it is "auto floated" windows set though the config?

**Comment by chrishoage** [comment] 2016-02-04 22:04
Ah, yes confirmed all my apps that are set to floating though `kwmrc` do not update. 

Windows that are given `float` work as expected.

**Comment by koekeishiya** [comment] 2016-02-04 22:06
Will look into it in a bit. Currently trying to figure out how to reliable reproduce a bug that causes Kwm to crash. I have no idea what triggers it yet, but it annoys me.

**Comment by chrishoage** [comment] 2016-02-04 22:08
It has been annoying me too. I have not found _exactly_ what causes it. It happens in a lot of situations: Sometimes when changing focus, sometimes when no input is happening and everything is just sitting there. 

No rhyme or reason. I've been trying to find out how to reproduce the crash at will but no luck so far.

**Comment by koekeishiya** [comment] 2016-02-04 22:10
I believe it starting happening after I made changes to support UTF8 encoding. I can not say for sure as I cannot reproduce the crash on demand. Can take anywhere from minutes -> days before it happens for me, which is a shame.

**Comment by chrishoage** [comment] 2016-02-04 22:12
For me it appears to happen _most_ often when changing display focus with the mouse. At least it appears that way. (It happened seconds before writing this)

With that said I've seen it crash with out moving the mouse between displays.

**Comment by koekeishiya** [comment] 2016-02-04 22:15
It happens to me regularly while only using the laptop display, so not sure if they occur for the same reason. I'm in the process of reviewing the entire codebase at this point, cleaning up how different functions are meant to interact, where error-checking occurs and adding assertions. This is gonna take some time, but I feel like it would help being able to iron out where fatal mistakes occur.

**Comment by koekeishiya** [comment] 2016-02-04 22:17
Border should now update for auto-floated / kwmrc-floated applications as well.

**Closed** 2016-02-04 22:17 UTC

**Comment by koekeishiya** [comment] 2016-02-04 22:21
Created #148 regarding the random crashes.
