### ISSUE TITLE
Retile windows after toggling monocle subtree off

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#341] opened 2016-04-27 15:41 UTC
After toggling a monocle node back to tiling mode, the windows that were in the subtree should retile.

**Comment by koekeishiya** [comment] 2016-04-27 15:44
The current behaviour was done so on purpose and is working as intended.
I often switch the mode back to bsp-type such that I can perform a normal bsp-split for the entire monocle-subtree.

**Comment by matthewdias** [comment] 2016-04-27 15:58
ah ok. also, shouldn't the `window -f` commands treat the monocle node as one target? Right now they just cycle through the monocole nodes, so you can't focus other windows. I thought that the `window -fm next/previous` commands were there for this reason.

**Comment by koekeishiya** [comment] 2016-04-27 16:04
> shouldn't the window -f commands treat the monocle node as one target?

Ideally, yes. The current implementation (of directions) only looks at windows and not which container they are associated with it, which is the problem here.

**Comment by koekeishiya** [comment] 2016-04-28 14:00
> ah ok. also, shouldn't the window -f commands treat the monocle node as one target? Right now they just cycle through the monocole nodes, so you can't focus other windows. I thought that the window -fm next/previous commands were there for this reason.

Fixed on master.

**Closed by koekeishiya** 2016-04-28 14:00 UTC
