### ISSUE TITLE
Chaning screen focus resets monocle focus

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#118] opened 2016-01-25 20:32 UTC
When using `screen -f next | prev` or when using mouse to change screen focus the focused monocle window resets to 0. 

So for example if I am on [3/3] and I change focus to display 0, the monocle display 1 changes to [1/3]. This happens with any screen focus method.

**Comment by koekeishiya** [comment] 2016-01-25 20:41
Was it always like this, or is this something that happeend recently?
I don't use anything but BSP myself, so I have no idea.

**Comment by chrishoage** [comment] 2016-01-25 20:41
Uh, odd, after closing some windows (but not all) I am not longer able to repo this issue. 

really unsure what happened.

**Comment by koekeishiya** [comment] 2016-01-25 20:41
I'll look into it regardless, there very well could be some issues here.

**Comment by chrishoage** [comment] 2016-01-25 20:43
> Was it always like this, or is this something that happened recently?

Something that happened in the last 24 hours. I had never experienced this issue before. 

I closed 2 out of 3 windows and opened them again, after that focus stuck when changing screen focus.

**Comment by koekeishiya** [comment] 2016-01-25 20:47
I don't believe I've made any changes related to this in a long time.
I'm unable to reproduce as well.

I'll simply close this for now I guess, feel free to create a new issue if you can reproduce on demand later.

**Closed by koekeishiya** 2016-01-25 20:47 UTC
