### ISSUE TITLE
Regression in mouse focus screen

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#100] opened 2016-01-20 21:49 UTC
Sometimes (I have not figured out what triggers it yet) when moving the mouse from display 1 to display 0, the tree on display 0 gets reset. Issuing a `tree -c refresh` does not fix it. (luckily I can just restore the tree!)

**Comment by koekeishiya** [comment] 2016-01-20 22:03
Does this only happen when using the mouse?
I have not experienced this in ages, so I assumed it was fixed.

**Comment by chrishoage** [comment] 2016-01-20 22:10
No, if I "abuse" `screen -f next | prev` kwm appears have quite high CPU usage and lags out, but the behavior doesn't happen.

However, during this "lag" kwm appears to ignore key commands. If I hit `cmd+alt-h` during this lag all windows hide (which is default OS X behavior)

The tree destruction issue only happens when changing focus across displays with the mouse.

**Comment by koekeishiya** [comment] 2016-01-20 22:18
Nothing I can do about that lag really if it is spammed,  except maybe prevent the user from using the command "that often".

I have no idea what or why the mouse bug still happens, as I have not experienced this since that last rewrite. I'll keep it in mind for the future, however I really doubt that it is something I can make any better than it currently is.

**Comment by chrishoage** [comment] 2016-01-20 22:23
Sounds good, it really does appear to be a regression of some kind. I had not had this happen again until very recently. With in the last few days.

**Comment by chrishoage** [comment] 2016-01-20 22:34
I actually can reproduce this fairly easily. I just use the mouse to change focus between screens. 

Once this happens any tree state that each display had is lost and reset (My config sets display 1 to monocle, to test this I changed display 1 to bsp and when the issue happened it changed back to monocle). 

To reproduce this use the mouse to focus display 1 then very quickly refocus display 0. This will cause the tree to reset.

**Comment by koekeishiya** [comment] 2016-01-20 22:43
Still unable to reproduce for some reason.

I have 5 windows on my laptop (screen 0), 2 windows on my external (screen 1)
Using the mouse to give focus to display 1 and quickly refocus display 0, nothing happens.

**Comment by chrishoage** [comment] 2016-01-20 22:47
I have to repeat the `Screen 0` - `Screen 1` - `Screen 0` process a few times, but after a few repeats of this sequence the tree on `screen 0` resets. 

But it's very very reproducible for me following that sequence. Doesn't take more than 10 tries. Sometimes happens after 2 or 3

**Comment by chrishoage** [comment] 2016-01-20 22:53
Here is my kwmrc settings. maybe it has to do with a specific one, (mouse-follows for example?)

```
# Set default values for screen padding
kwmc config padding top 40
kwmc config padding bottom 60
kwmc config padding left 20
kwmc config padding right 20

# Set default values for container gaps
kwmc config gap vertical 20
kwmc config gap horizontal 20

kwmc config focused-border enable
kwmc config focused-border color ff6699cc
kwmc config focused-border size 6

kwmc config marked-border enable
kwmc config marked-border color ffec5f67
kwmc config marked-border size 6

# Let Kwm listen for hotkeys
kwmc config hotkeys enable

# Turn off focus-follows-mouse if any
# context-menus or the menubar is visible.˛˛˛
# If the menubar is not set to auto-hide,
# disable this setting.
kwmc config menu-fix disable

# Set focus-follows-mouse-mode to autoraise
kwmc config focus autoraise

# Set mouse-follows-focus
kwmc config focus mouse-follows enable

# Disable autorise when a floating widnow is focused
kwmc config focus standby-on-float enable

# Window can be made floating through drag&drop
kwmc config dragndrop disable

# Allow Kwm to tile windows
kwmc config tiling enable

# Default tiling mode for new spaces
kwmc config space bsp

# Set default tiling mode for screens
kwmc config screen 0 bsp
kwmc config screen 1 monocle

# Wrap focus tos creen
kwmc config cycle-focus screen # all | disabled

# Add custom tiling rules for applications that
# does not get tiled by Kwm by default.
# This is because some applications do not have the
# AXWindowRole and AXStandardWindowSubRole
kwmc config add-role AXDialog iTerm2
kwmc config add-role AXDialog Zeplin

# Automatically float non-resizable applications
kwmc config float-non-resizable enable

# The following command blacklists a specific application
# from Kwms tiling (PS: The app name is case-sensitive)
# If the name consist of multiple words, the command
# looks like: kwmc config float Google Chrome
kwmc config float Steam
kwmc config float System Preferences
kwmc config float iStat Menus
kwmc config float QuickTime Player
kwmc config float zoom.us
kwmc config float VLC

kwmc config capture 1 Slack
kwmc config capture 1 iTunes

kwmc config prefix ctrl-k
kwmc config prefix-global disable
kwmc config prefix-timeout 0.75

# Toggle autoraise
kwmc bind prefix+cmd-t config focus toggle

# Refresh window position
# kwmc bind shift+alt+ctrl-r window -c refresh

# Refresh all windows
kwmc bind prefix+cmd+shift-r tree -c refresh

#Quit kwm
kwmc bind prefix+cmd-q quit

# Mark window for next split
kwmc bind prefix-m window -t mark

# Toggle horizontal and vertical split for window
kwmc bind prefix-s window -c split

# Toggle window fill screen
kwmc bind prefix-f window -t fullscreen

# Toggle window fill parent container
kwmc bind prefix-p window -t parent

# Toggle window float
kwmc bind prefix-w window -t float

# Move marked window to new leaf at focused window
kwmc bind prefix-x window -x

# Move focused window to screen
kwmc bind prefix+cmd-1 screen -m 0
kwmc bind prefix+cmd-2 screen -m 1

# Change space to Binary Space Partitioning (default)
kwmc bind prefix+cmd-b space -t bsp

# Change space to monocle (full screen windows)
kwmc bind prefix+cmd-f space -t monocle

# Change space to floating windows (normal)
kwmc bind prefix+cmd-w space -t float

# Rotate tree clockwise?
kwmc bind prefix+cmd-r tree -r 90

# Move Focus
kwmc bind cmd+alt-j window -f prev
kwmc bind cmd+alt-k window -f next

# Move Screen Focus
kwmc bind cmd+alt-h screen -f prev
kwmc bind cmd+alt-l screen -f next

# Move Window
kwmc bind cmd+alt-p window -s prev
kwmc bind cmd+alt-n window -s next

# Change pane size
kwmc bind prefix+shift-h window -c reduce 0.1
kwmc bind prefix+shift-l window -c expand 0.1
kwmc bind prefix-h window -c reduce 0.05
kwmc bind prefix-l window -c expand 0.05

# Change Gaps
kwmc bind prefix-x space -g increase horizontal
kwmc bind prefix-y space -g increase vertical

kwmc bind prefix+shift-x space -g decrease horizontal
kwmc bind prefix+shift-y space -g decrease vertical

kwmc bind prefix-leftarrow space -p increase left
kwmc bind prefix-rightarrow space -p increase right
kwmc bind prefix-uparrow space -p increase top
kwmc bind prefix-downarrow space -p increase bottom

kwmc bind prefix+shift-leftarrow space -p decrease left
kwmc bind prefix+shift-rightarrow space -p decrease right
kwmc bind prefix+shift-uparrow space -p decrease top
kwmc bind prefix+shift-downarrow space -p decrease bottom

# Open iTerm2 window
kwmc bind prefix-return sys /Users/chrishoage/bin/open-iTerm.applescript
kwmc bind prefix-c tree restore code

```

**Comment by koekeishiya** [comment] 2016-01-20 22:56
With the exception of screen capture, binds and the following
```
kwmc config screen 0 bsp
kwmc config screen 1 monocle
```
our config has the same settings, so if anything its some conflict with one of these.

**Comment by koekeishiya** [comment] 2016-01-20 23:01
Do you happen to have kwm managed by launchd?
I dont think this is the same bug as before, rather I have managed to make Kwm actually crash by doing your described behaviour for a longer period of time.

It appears that kwm-overlay gets passed a nil-value and Kwm segfaults shortly after.
Can you try reproduce on your side with all borders turned off?

**Comment by chrishoage** [comment] 2016-01-20 23:03
>  Kwm segfaults shortly after

That sounds like it would cause my issue. If KWM crashes `launchd` would restart it. This would explain the behavior I was seeing.

**Comment by koekeishiya** [comment] 2016-01-20 23:05
Debug output while doing said behaviour mouse-focusing, this is a segment of the last output.

```
SetWindowRefFocus() Focused Window: borderless (bash)
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
SetWindowRefFocus() Focused Window: Koe
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 1
Populated Screen Key/Mouse Focus
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
SetWindowRefFocus() Focused Window: Koe
ShouldBSPTreeUpdate() Remove Window
UpdateFocusedBorder()
fatal error: unexpectedly found nil while unwrapping an Optional value
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
SetWindowRefFocus() Focused Window: Koe
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
```
Kwm just simply stops running after that last line, does not show a segfault or send the SIGSEGV code to Kwm.

**Comment by chrishoage** [comment] 2016-01-20 23:05
> It appears that kwm-overlay gets passed a nil-value

This appears to happen because _sometimes_ (this explains the inconsistency) my mouse would land on the desktop (padding area). 

Landing on the desktop and moving back reproduces this 100% of the time

**Comment by koekeishiya** [comment] 2016-01-20 23:06
Is it possible to just fix this within kwm-overlay? Not really sure where in Kwm I'd have to look, as I have done checks for valid focus already in these areas.

**Comment by koekeishiya** [comment] 2016-01-20 23:13
Nvm I can reproduce this bug with borders disabled. I have an idea of why this happens, I made some changes recently that could be the cause, which is why this is the first time this bug has "re-occured".

**Comment by chrishoage** [comment] 2016-01-20 23:14
Ok good because I was about to say even if a null / missing windowId is passed to the overlay it should just default to 0 width / height / x / y, not crash. 

Really not sure why that crash happens in kwm-overlay.

**Comment by koekeishiya** [comment] 2016-01-20 23:16
Do you happen to have some script running that calls `kwmc read focused`or `kwmc read tag`?
I believe this is where the issue is/was.

**Comment by chrishoage** [comment] 2016-01-20 23:16
I do indeed! My bitbar script reads it.

**Comment by koekeishiya** [comment] 2016-01-20 23:19
Ok so basically what I believe has happened is, I made it so that Kwm clears its focus when there actually is no window focused (mid-screen transition, mid-space transition), or just simply closing a window and there are none left under the curosor or focused by OSX.

I forgot to check in the read code mentioned if Kwm actually has focus. After doing this I can no longer reproduce the crash (yet at least..).

**Closed** 2016-01-20 23:22 UTC
Labels: bug

**Comment by chrishoage** [comment] 2016-01-20 23:26
Confirmed, that fixed it.
