### ISSUE TITLE
Install and setup

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#44] opened 2016-01-06 06:23 UTC
To install kwm currently one has to check out the repo, `make` the binary, then run kwm. This shows in Accessibility as `iTerm` for me, and must be granted Accessibility access again when `launchd` runs it as kwm. I feel that this could be simplified. 

I am willing to bet that the kind of person who is interested in kwm also has Homebrew installed. By making Homebrew the suggested way of installing kwm you would be able to remove the `kwmc config launchd enable | disable` code and handle that though documentation / homebrew. 

```
brew install kwm
# Brew shows caveats with message about examples directory
# and commands to run to start kwm at login. 
ln -s /usr/local/opt/kwm/*.plist ~/Library/LaunchAgents/
launchctl load -w ~/Library/LaunchAgents/com.koekeishiya.kwm.plist
# Accessibility challenge for kwm
```

vs

```
git clone https://github.com/koekeishiya/kwm.git
cd kwm
make install
./bin/kwm
# Accessibility challenge for iTerm
# New iTerm window
./bin/kwmc  config launchd enable
# Accessibility challenge for kwm next log in. 
```

Homebrew would make updating simpler too

```
brew update kwm
kwmc quit
```

vs

```
git pull
make install
./bin/kwmc quit
```

If you insist on keeping `kwmc config launchd enable` then perhaps add a `kwmc start` to go along with `kwmc quit`? 

It looks like there is a pull request out to get kwm into Homebrew but has some feedback that needs to be addressed. https://github.com/Homebrew/homebrew/pull/47459. You may need to make some changes to the Makefile to support `prefix` in order for the PR to be accepted. Once the needed updates are made I can make sure the PR for Homebrew gets merged.  

Documentation would be updated to promote the Homebrew installation method and add an alternative manual install method (that include optionally copying the plist and kwmrc to the correct locations). 

What are your thoughts on all this?

**Comment by koekeishiya** [comment] 2016-01-06 09:15
See https://github.com/koekeishiya/kwm/issues/23

Makefile should already be good to go.
The problem with removing the launchd option and moving it to homebrew,
is more or less the fact that people that do not use homebrew would be able to opt-in for the launchd system.

Personally I don't really have an opinion on this.

**Comment by chrishoage** [comment] 2016-01-06 18:39
> But I think this requires maintaining 2 .plist files because there is no way to tell ahead of time where the user will place the binaries.

This is why I think it should be a) suggested people install though `brew` because it would handle all that for the user along with generating the correct `plist`, no maintenance on your part required. 

For users that do no wish to use homebrew I can see kwm offering one of two things: Either a) Documentation with one-liner bash commands.

KWM Docs:
```bash
# Installing KWM with out Homebrew:
git clone https://github.com/koekeishiya/kwm.git
cd kwm
make install
# If you wish to start kwm at login run the following commands
# Update the plist with the path to kwm. 
sed -i "s/\/path\/to\/kwm/$(pwd)/bin/kwm/" kwm.plist #this sed command is mostly made up but this is the gist of it
cp kwm.plist ~/Library/LaunchAgents/
launchctl load ~/Library/LaunchAgents/kwm.plist
# Accept kwm accessibility permissions. 
```

My reasoning for this is it removes a lot of the launch management from kwm itself (thus simplifying the code). The launchctl step is something that would only have to be set up once, and anyone who is comfortable enough to git clone and make install should also be able to run 3 extra commands to run at login. However if you do not want to remove the launchd option from kwm I understand.  

I will try and shepherd the PR for homebrew to get merged. I will then submit a PR with doc updates for your review. 

Thanks!

**Comment by chrishoage** [comment] 2016-01-06 18:44
@napcae What is the status of the Homebrew PR feedback? If you need someone to take over that for you please let me know.

**Comment by chrishoage** [comment] 2016-01-07 22:31
Something I have noticed and wasn't sure if it was a problem with something I was doing or not: Every time I pull and rebuild kwm (or what `update` would do in homebrew) I have to grant kwm Accessibility access again. Is there any way around that issue? Does it have to do with being a binary and not an application bundle?

**Comment by koekeishiya** [comment] 2016-01-07 22:46
This is a part of the security mechanism implemented by OSX and there is no way around this as far as I know. When Kwm gets recompiled, the signature of the binary changes, and thus must be granted access again.

**Comment by chrishoage** [comment] 2016-01-07 22:48
I have other applications that request Accessibility access and when those update do not request it again. I'm guessing that is due to code signing?

**Comment by koekeishiya** [comment] 2016-01-07 22:52
I haven't really looked into it too much, so I can't say how they do it. I have no prior experience with developing on OSX before this project either.

**Comment by chrishoage** [comment] 2016-01-07 23:09
Good to know, I can start code signing it myself no problem. Though I wonder for a much longer term solution turning this into a distributed `.app` (application bundle) might be worth doing? The binary can be distributed along with the source code how [Amethyst](https://github.com/ianyh/Amethyst) is distributed.

**Comment by a-morales** [comment] 2016-01-08 18:47
I've also been doing some reading on code signing for a more long term solution. Seems that whenever a new release is done a prebuilt binary can be used in which can have the code signed. This prebuilt binary can then be specified as a [Homebrew bottle](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#homebrew-terminology) in which homebrew will install the prebuilt and signed binary instead of building from source and thus avoiding having to give Kwm accessibility permission on every update

**Comment by chrishoage** [comment] 2016-01-08 19:14
Good find, a Homebrew Bottle distributed though the github releases system might be the best bet. [Here is more documentation on bottles](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md)

**Comment by chrishoage** [comment] 2016-01-10 19:47
Just to confirm: I have started to `codesgin` after making the binary and it has stopped asking for Accessibility permissions aside from the first launch. 

Using homebrew bottles and distributing a codesigned binary though github sounds like the best idea for a long term solution.

**Comment by koekeishiya** [comment] 2016-01-18 21:49
Forgot this was a thing, my bad.

I have confirmed as well that a codesigned  binary does not ask for accessibility permissions after being enabled once.

I can indeed provide a codesigned binary for use with homebrew if that is requested. However, I have no idea how really how homebrew formulas work or what they require really, so I'll leave that up to some of you guys.

**Comment by chrishoage** [comment] 2016-01-18 21:52
> I can indeed provide a codesigned binary for use with homebrew if that is requested. However, I have no idea how really how homebrew formulas work or what they require really, so I'll leave that up to some of you guys.

I have pretty much just been waiting for codesigned binaries to be distributed though a zip file in GitHub Releases. 

Once these binaries are available I will make a new PR for homebrew that uses the bottle.

**Comment by koekeishiya** [comment] 2016-01-18 22:00
Aight sorry about that.

A codesigned binary release can be found here:
https://github.com/koekeishiya/kwm/releases/tag/v1.0.8

Updates for Kwm will probably not be as frequent anymore, as my courses at university have just started again. This leaves me with quite little time to work on Kwm. More changes will be coming, but at a much slower rate.

**Comment by chrishoage** [comment] 2016-01-18 22:03
I'll tackle the homebrew formula either in a few hours or tomorrow. 

However I did notice that the default `kwmrc` did not appear to be in the pre built release, which might be useful to include.

**Comment by koekeishiya** [comment] 2016-01-18 22:04
Good catch, fixed that now.

**Comment by chrishoage** [comment] 2016-01-18 23:28
Just an FYI to anyone watching this ticket, `homebrew` will not be able to be used. I will need to submit this to `homebrew-binary` instead. 

We can still submit to homebrew, however the binary can not be.

**Comment by chrishoage** [comment] 2016-01-24 01:17
https://github.com/Homebrew/homebrew-binary/pull/290

Created PR to homebirew binaries. When / if this is accepted I will update the documentation to reflect the new installation process. 

A new codesigned binary should be built and a new version released soon because there have been some important bug fixes since the 1.0.8

**Comment by koekeishiya** [comment] 2016-01-24 01:28
Released 1.0.9 to get in a couple of the important fixes, also includes codesigned binary.

**Comment by abienz** [comment] 2016-02-01 17:26
The submission on Homebrew has been closed with a few changes to the submission left unfulfilled. Is there any chance to get this reopened and installing through Homebrew?

https://github.com/Homebrew/homebrew/pull/47459

**Comment by chrishoage** [comment] 2016-02-01 17:36
I have a PR out to the homebrew-binaries tap already. See the link 2 comments above yours @abienz

**Comment by koekeishiya** [comment] 2016-02-15 07:24
I'm getting close to a point where I feel like Kwm is very stable for daily use, with the exception of changing montior arrangements without restarting Kwm. 

Because of this, changes that I do from now on will probably not be as important to get immediately, and so it might be more realistic to get Kwm in the main homebrew repository despite not getting codesigned binaries, if this is something people are still interested in.

**Comment by chrishoage** [comment] 2016-02-15 07:37
I have been following though with the `homebrew-binary` very recently. That should be merged in very soon. 

I personally think it is very annoying to update kwm with out codesigning to the point where I have my own `kwm-update` script that pulls, compiles, and code signs for me. 

I am very unsure if homebrew [allows for duplicate packages](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions) when another tap has it already. 

> Because of this, changes that I do from now on will probably not be as important to get immediately

I think that's a pretty good reason to keep releasing built binaries that are code signed. People that want to run bleeding edge can download and install the OS X SDK and compile it themselves (and code sign it if they desire). 

If we can get it in both homebrew taps then that would be best, however if we have to choose between `homebrew-binary` and `homebrew` I would say `homebrew-binary` is more useful to more people.

**Comment by koekeishiya** [comment] 2016-02-15 07:39
Agreed with the points given above. I'll probably put out version 1.1.2 some time during this week. There has been quite some important changes.

**Comment by dominiklohmann** [comment] 2016-02-15 10:28
> I'm getting close to a point where I feel like Kwm is very stable for daily use, with the exception of changing monitor arrangements without restarting Kwm.

What about #123? Still a very big issue, because unless you're using external tools like [gfxCardStatus](https://gfx.io) you have no way to tell what happened and why kwm reset. I wouldn't consider that stable for everyones daily use to be honest.

**Comment by koekeishiya** [comment] 2016-02-15 10:31
> What about #123? Still a very big issue, because unless you're using external tools like gfxCardStatus you have no way to tell what happened and why kwm reset. I wouldn't consider that stable for everyones daily use to be honest.

This is an issue I can't really work on unless it can be connected directly with some other issue I can debug, as I do not have a macbook with a dGPU

**Comment by koekeishiya** [comment] 2016-02-15 17:02
The PR for homebrew/binary has been merged and I've updated install instructions to reflect these changes.

**Closed by koekeishiya** 2016-02-15 17:02 UTC
Labels: enhancement

**Comment by koekeishiya** [comment] 2016-02-15 17:13
The plist generated through the formula use `/usr/local/opt/kwm/kwm` as the path for the binary.
I've noticed that the directory `/usr/local/opt/kwm` is not created, and it does not contain the kwm binary nor the plist file itself.

If the actual binary itself is copied, and not symlinked, I believe the kwm-overlay binary has to be copied in to the opt directory as well as Kwm the path of the binary to search for this file.

**Comment by chrishoage** [comment] 2016-02-15 17:24
Huh, the formula worked when I was testing. I was able to install and launch kwm though the instructions. I will have to investigate this issue.

**Comment by chrishoage** [comment] 2016-02-15 17:29
I just tested again and everything is working as expected. I am able to launch kwm though launchd using the `Caveats` listed post install. 

What issue are you seeing, I'm not sure I completely understand?

**Comment by koekeishiya** [comment] 2016-02-15 17:31
> ┌[オスムンド::~
└┤[18:28] ->>> brew install kwm
==> Installing kwm from homebrew/binary
==> Downloading https://github.com/koekeishiya/kwm/releases/download/v1.1.1/Kwm-1.1.1.zip
Already downloaded: /Library/Caches/Homebrew/kwm-1.1.1.zip
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/kwmc
Target /usr/local/bin/kwmc
already exists. You may want to remove it:
  rm '/usr/local/bin/kwmc'

> To force the link and overwrite all conflicting files:
  brew link --overwrite kwm

> To list all files that would be deleted:
  brew link --overwrite --dry-run kwm

> Possible conflicting files are:
/usr/local/bin/kwmc -> /Users/Koe/Documents/programming/C++/Kwm/bin/kwmc
==> Caveats
Copy the example config from /usr/local/Cellar/kwm/1.1.1/kwmrc into your home directory.
  mkdir -p ~/.kwm
  cp /usr/local/Cellar/kwm/1.1.1/kwmrc ~/.kwm/kwmrc

> To have launchd start homebrew/binary/kwm at login:
  ln -sfv /usr/local/opt/kwm/*.plist ~/Library/LaunchAgents
Then to load homebrew/binary/kwm now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.kwm.plist
==> Summary
🍺  /usr/local/Cellar/kwm/1.1.1: 6 files, 351.8K, built in 0 seconds
┌[オスムンド::~
└┤[18:29] ->>> cat /usr/local/opt/kwm
cat: /usr/local/opt/kwm: No such file or directory
`/usr/local/opt/kwm` does not exist

**Comment by chrishoage** [comment] 2016-02-15 17:32
```
chrishoage at Constance in ~
❯ brew install kwm
==> Installing kwm from homebrew/binary
==> Downloading https://github.com/koekeishiya/kwm/releases/download/v1.1.1/Kwm-1.1.1.zip
Already downloaded: /Library/Caches/Homebrew/kwm-1.1.1.zip
==> Caveats
Copy the example config from /usr/local/Cellar/kwm/1.1.1/kwmrc into your home directory.
  mkdir -p ~/.kwm
  cp /usr/local/Cellar/kwm/1.1.1/kwmrc ~/.kwm/kwmrc

To have launchd start homebrew/binary/kwm at login:
  ln -sfv /usr/local/opt/kwm/*.plist ~/Library/LaunchAgents
Then to load homebrew/binary/kwm now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.kwm.plist
==> Summary
🍺  /usr/local/Cellar/kwm/1.1.1: 6 files, 351.8K, built in 0 seconds

chrishoage at Constance in ~
❯ less /usr/local/Cellar/kwm/1.1.1/kwmrc

chrishoage at Constance in ~
❯ ln -sfv /usr/local/opt/kwm/*.plist ~/Library/LaunchAgents
/Users/chrishoage/Library/LaunchAgents/homebrew.mxcl.kwm.plist -> /usr/local/opt/kwm/homebrew.mxcl.kwm.plist

chrishoage at Constance in ~
❯ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.kwm.plist

chrishoage at Constance in ~
❯ launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.kwm.plist

chrishoage at Constance in ~
❯ brew uninstall kwm
Uninstalling /usr/local/Cellar/kwm/1.1.1... (6 files, 351.8K)

chrishoage at Constance in ~
❯ rm ~/Library/LaunchAgents/homebrew.mxcl.kwm.plist
remove /Users/chrishoage/Library/LaunchAgents/homebrew.mxcl.kwm.plist? y
```

I wonder if it has to do with your `Target /usr/local/bin/kwmc` error?

**Comment by koekeishiya** [comment] 2016-02-15 17:34
> I wonder if it has to do with your Target /usr/local/bin/kwmc error? 

So I deleted my previous symlink, and indeed this was the problem.
I guess the formula works as intended then.

**Comment by chrishoage** [comment] 2016-02-15 17:34
:+1:  _phew_
