### ISSUE TITLE
Restarting Event Tap causes laggy key input

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#327] opened 2016-04-21 16:58 UTC
I'm reviving #92 because I am now very confident that the "laggy key input" issues I am seeing are directly related to `Restarting Event Tap` logs that happen. 

I still have not found out how to reliably reproduce the `Restarting Event Tap` log yet, but when it does happen, they are logged 2-5 times in a row and NO key input gets though during these logs. 

Once these logs stop happening all key presses get delivered at once.

**Comment by koekeishiya** [comment] 2016-04-26 14:48
I believe the "restarting event tap" happens when an application (does not matter which) enters a non-responding state for a short while. I can reproduce this on demand with `Firefox`, when navigating between two `resource heavy` pages. Trying to switch focus away during this moment (using the trackpad) does not work and I suspect this would cause keybinds and tiling of new windows to also halt.

I guess a solution for the above would be to make every single part of Kwm be able to run asynchronously, and write actual proper multi-threaded code.

**Comment by chrishoage** [comment] 2016-04-26 18:28
> enters a non-responding state for a short while.

That makes sense, and is inline with the behavior I have been seeing now that you mention it.

**Comment by koekeishiya** [comment] 2016-08-13 12:14
I suspect this problem could be solved by using `RegisterEventHotkey` (the carbon system) instead of the more modern event taps. This does however reduce the flexibilty of the binding system, or at least makes it a lot more tricky to maintain the current functionality.

**Comment by chrishoage** [comment] 2016-08-13 22:30
Actually haven't seen this issue happen much (at all?) since v3.

**Comment by koekeishiya** [comment] 2016-08-30 18:56
I'm gonna go ahead and close this issue, as I have not experienced this since v3 as well, as far as I can remember.

Also after investigating event taps some more, this is not something that is "fixable" as long as the hotkey system relies on event taps.

**Closed by koekeishiya** 2016-08-30 18:56 UTC
Labels: bug
