### ISSUE TITLE
iterm2 window issues

### ISSUE THREAD

**Issue by Speaky10k** [koekeishiya/kwm#36] opened 2016-01-03 01:02 UTC
For whatever reason, a space with only iterm2 windows open will become somewhat unreadable by kwm.  Opening another window will fix it for the duration that the other window is on screen, but once it's back to only iterm2 windows it's immediately dead after dying once.  The only command it seems to respect in this state is to rotate the windows.  If it helps, kwmc focused responds with whatever non-iterm window was last focused.

**Comment by koekeishiya** [comment] 2016-01-03 01:17
iTerm2 windows tile just fine for me, and have done so since the first beta.
Gonna need more detailed information if I'm gonna be able to reproduce.

**Comment by Speaky10k** [comment] 2016-01-03 15:41
Upon further investigation it's not just the iterm windows that are being affected, it's any windows that were open previous.  KWM will often detect new windows but fail to see any opened previous.  A logout fixes it if running through launchd.  Sorry, I don't have the debug output handy here, but it was an error about not having a window in focus (would only show when receiving a command).  Anything else I can do to help?

**Comment by koekeishiya** [comment] 2016-01-03 15:52
Uh what do you mean by open previous?
As windows that are open before Kwm is started?

Does this also happen in the latest commit (just clone from current master and rebuild)

**Comment by Speaky10k** [comment] 2016-01-03 21:12
*something* happens where KWM loses track of the windows that are open.  When this occurs, any of  the windows that are already open are mostly invisible to it--KWM won't see them when they're focused and won't manipulate them directly.  What KWM can do, in these circumstances, is detect new windows that are opened and tile the space accordingly--it will see that it needs to resize windows that already exist and do so, and then the new window can be swapped with any of the open windows but only from the new window.  Any commands that are sent with another window focused give an error stating that no window is in focus.  I cannot seem to pinpoint what, exactly, causes this as there's nothing logged to show when it starts (and I don't notice until I send a command that fails).

**Comment by koekeishiya** [comment] 2016-01-03 21:17
This sounds like a really awkward bug.

Do you happen to be using multiple monitors when this happes?
Do you have "Automatically rearrange Spaces based on most recent use" and so on checked in Mission Control settings?

Does this happen during regular use, or only after coming out of sleep mode or something?

I have no clue really where to start looking, however at first glance it would seem like an issue with spaces.

**Comment by Speaky10k** [comment] 2016-01-03 21:27
It happens during regular use, and I do use multiple monitors but it will occur when there isn't a second monitor present as well.  The only check box on Mission Control Prefs that is on is "Displays have separate spaces," 
Automatically rearrange Spaces based on most recent use, 
When switching to an application, switch to a Space with open windows for the application, and 
Group windows by application 
are all disabled as is the dashboard.
Could it be the separate spaces (the second display continues the sequential numbering of spaces where the first leaves off, so I didn't think it would be an issue)?

**Comment by koekeishiya** [comment] 2016-01-03 21:30
I use the exact same settings, so that should not be a problem then.
I have not personally had a chance to test how Kwm behaves with multiple monitors yet, which is why that could be it, but appearntly not.

At this point I do think "Secure Keyboard Entry" could be the issue.
What this does is basically disable accessiblity functionality.
I know for a fact iTerm does have this (can be disabled).

**Comment by Speaky10k** [comment] 2016-01-03 21:41
I'll disable the secure keyboard entry in iterm and continue monitoring, if that fixes it or if I get a more precise view of when this is occurring I'll let you know.  If there's anything specific with multiple monitors you want tested (or you think might fix/be the cause of this), I'd be happy to oblige.

**Comment by koekeishiya** [comment] 2016-01-03 21:45
Nothing more that I can think of at the moment. I'll keep this issue open for now, thanks.

**Comment by vemek** [comment] 2016-01-03 23:55
Just chiming in - I had similar problems, no Kwm shortcuts working when an iTerm2 window was focused. This issue led me to realise that I had accidentally enabled Secure Keyboard Entry by entering Cmd+Alt+S when Kwm wasn't running. Fixed by turning it off and restarting the daemon. Thanks!

**Comment by koekeishiya** [comment] 2016-01-05 13:42
I'm gonna assume the problem was indeed Secure Keyboard Entry.

**Closed by koekeishiya** 2016-01-05 13:42 UTC
