### ISSUE TITLE
Add support for windows that have been hidden, minimised or moved between Spaces

### ISSUE THREAD

**Issue by mottram** [koekeishiya/kwm#94] opened 2016-01-20 11:36 UTC
When hiding, minimising or moving a window to another space, kwm gets very confused:

Hiding or minimising a window causes kwm to lose track of it. Sometimes, but not always, clicking on a window then floating/unfloating it will bring it back under kwm's control.

When moving a window between spaces, it isn't added to the tree in the new space, and moving a window from one space to another moves it to the bottom right corner of the screen. This glitch repeats, so a window moved across multiple spaces ends up being shunted offscreen, like so:

<img width="1680" alt="screenshot 2016-01-20 10 51 51" src="https://cloud.githubusercontent.com/assets/146043/12447747/96bc033a-bf69-11e5-9dc6-4be16024b12f.png">

If window borders are enabled, hiding/minimising and moving between spaces leaves 'ghost' borders on screen in the window's original position, or roughly in the vicinity of the window's new position.

It'd be lovely if kwm 'knew' about hiding, minimising and space-related movements, so that windows being unhidden, moved, &c. were treated the same as newly-opened windows.

**Comment by koekeishiya** [comment] 2016-01-20 11:44
There are no APIs for moving windows between spaces, so this is not something I can do.
I can have Kwm perform the keyboard shortcuts "cmd+n" to move a window to the nth space, but this is not a good way to do it.

For Kwm to behave properly with moving windows between spaces;
> What I usually do if i have to send a window to a different space, is make it floating, open mission control and drag it to the space i want, select my new insertion point and un-float it.

See https://github.com/koekeishiya/kwm/issues/37

**Comment by mottram** [comment] 2016-01-20 12:19
> There are no APIs for moving windows between spaces, so this is not something I can do.

I didn't mean that kwm should provide keyboard shortcuts for moving windows between spaces, but that it should tile windows that have been moved.

> What I usually do if i have to send a window to a different space, is make it floating, open mission control and drag it to the space i want, select my new insertion point and un-float it.

Yep, I've been using that workaround, except I'm using [BetterTouchTool](http://www.boastr.net) to move windows to the next/previous space with a keyboard shortcut. Unfortunately, un-floating the window after moving it causes the 'ghost border' problem that also crops up when hiding/miinimising:

<img width="1680" alt="screenshot 2016-01-20 12 07 27" src="https://cloud.githubusercontent.com/assets/146043/12448531/857e3138-bf6e-11e5-9b2e-acaf7f32b5d8.png">

Sorry I wasn't clear - I'd like kwm to keep track of windows that have been hidden, minimised or moved to another screen, instead of going haywire whenever a window is un-hidden, un-minimised, &c.. Would that be possible?

**Comment by koekeishiya** [comment] 2016-01-20 12:35
I'm unable to reproduce the border issue, does it happen with commands such as `window -t fullscreen` and so on?

Dealing with hidden and minimized windows are a pain, and to be honest I dont see much use for this behaviour with tiling involved.

Out of curiosity, how do these things affect your workflow, when/why are they useful in a tiling setup?

**Comment by mottram** [comment] 2016-01-20 14:26
> I'm unable to reproduce the border issue, does it happen with commands such as window -t fullscreen and so on?

fullscreen works fine, unless I'm moving a fullscreen'd window to another space. The ghosting happens when moving windows between spaces, or when un-minimising/un-hiding/un-floating a window in a space with existing windows.

> Out of curiosity, how do they affect your workflow, when/why are they useful in a tiling setup?

I hide applications and minimise windows constantly. If I'm writing in a text editor and need to look something up on the web, I'll open a browser window and search, then minimise that browser window for later reference. Or I might need to do something quickly with a specific open app, so I'll switch to it, do the task, then hide the app until I need it again. I use 'Hide Others' a lot, too, when I've been working with several apps for a short time and then want to return to the main app I was using before. I also regularly switch to a clean space and un-hide/un-minimise stuff there, so as not to disturb the window arrangements on other spaces. 

In other words, most of the time I have two or three windows visible and everything else is lurking ought of sight, ready to be brought onto the screen when I need it, so hiding and minimising are as useful to me as changing window focus or position.

This way of working is probably down to running [dwm](http://dwm.suckless.org) for many years - it doesn't have spaces or desktops in the usual sense, instead you 'tag' windows and use those tags to push and pull windows on and off screen, or show more than one tag on screen at once.

Also, I use a laptop, so there just isn't room to do the 'traditional' tiling workflow of leaving loads of windows open all at the same time and navigating between them. I imagine most folk using a tiling WM on a smaller screen or monitor work in a similar way - without hiding windows or moving them to other spaces, you'd have to quit apps and close windows to avoid cluttering up the screen.

**Comment by koekeishiya** [comment] 2016-01-20 14:33
Aright good points, I can see how that may be useful indeed.

Again I am very limited to how much impact I can have regarding hiding, minimizing and detect changes between spaces, but I'll try to look into later today and see if there may be something to do that allows Kwm to handle that kind of use.

I may very well have to make kwm commands for it, as that gives me more flexibility to update the state of Kwm itself, instead of trying to monitor changes performed by external applications (which is very very limited).

**Comment by mottram** [comment] 2016-01-21 09:28
> I'll try to look into later today and see if there may be something to do that allows Kwm to handle that kind of use.

Brilliant - thanks!

**Comment by matthewdias** [comment] 2016-02-10 05:43
If any headway is made on this, some keyboard control for spaces would be nice. Besides moving a window to a specific space as mentioned above, moving to the previous space (similar to cmd+tab), as well as deleting the current space. (on keypress or when no windows are left, and you are not on the last space.)

**Comment by koekeishiya** [comment] 2016-02-10 05:57
>  moving to the previous space (similar to cmd+tab)

This was made possible in a recent commit. See `kwmc space -s id num`.
To go to a previous / next space, see `kwmc press`.

To use `kwmc space -s .. ..` you need to enable OSX space shortcuts in system preferences, and set the modifiers selected using `kwmc config spaces-key mod+mod+mod`, e.g: `kwmc config spaces-key cmd+ctrl`.

If you enable the prev/next shortcuts as well, say ctrl+left arrow, the command `kwmc press ctrl-left` will perform the space change.

I plan on looking into creating a system to make Kwm more scriptable, so that users can run some script when a certain action is triggered or a certain state is reached (for example all windows on the current space are closed).

**Comment by matthewdias** [comment] 2016-02-10 06:01
great, thanks. More events for scripting are always appreciated.

**Comment by matthewdias** [comment] 2016-02-10 06:06
When I said "previous space", tho, I meant going back to the previous space that you are on. For example, if I'm on space 3, and I switch to Chrome on space 1, press key to go back to space 3.

**Comment by strages** [comment] 2016-02-25 13:05
Does this issue include the glitching effect when using the scale or suck animation for de-minimizing apps from the dock.

When bps is active it already tries to fit the "still scaling" window in to its tree. The result is a double resize of the window from the dock, one really small and then a good one. when going to not bps modes like monocle, this is gone.

**Comment by koekeishiya** [comment] 2016-03-09 00:08
> When moving a window between spaces, it isn't added to the tree in the new space, and moving a window from one space to another moves it to the bottom right corner of the screen. This glitch repeats, so a window moved across multiple spaces ends up being shunted offscreen

This should be fixed and officially supported by Kwm now.
See my comment in #219 for how to configure this.

> .. except I'm using BetterTouchTool to move windows to the next/previous space with a keyboard shortcut.

If BetterTouchTool is used to move a window between spaces, Kwm will not be able to update its window-trees properly, and so I would recommend using the built-in Kwm way described above.

**Comment by koekeishiya** [comment] 2016-03-09 00:12
>  Does this issue include the glitching effect when using the scale or suck animation for de-minimizing apps from the dock.

> When bps is active it already tries to fit the "still scaling" window in to its tree. The result is a double resize of the window from the dock, one really small and then a good one. when going to not bps modes like monocle, this is gone.

I will look into this when I have time, however I have had no issues with this using the Genie effect (at least I don't notice that there is an issue here).

**Comment by koekeishiya** [comment] 2016-03-09 00:16
> moving to the previous space (similar to cmd+tab)

I'm not sure yet if this is doable, but will look into it in the future.

> as well as deleting the current space. (on keypress or when no windows are left, and you are not on the last space.)

There is a private function `CG_EXTERN void CGSSpaceDestroy(CGSConnectionID cid, CGSSpaceID sid);`, however I have no idea if this still works/exists. Will look into trying this.

**Comment by koekeishiya** [comment] 2016-03-22 16:24
How many of the original problems in this issue is still a problem in the latest commit?

**Comment by matthewdias** [comment] 2016-03-22 23:00
Minimizing works fine and retiles with any method, until a bring back from minimize is missed by kwm, at which point the app that is re-minimized retains focus after minimizing.

Bringing back from minimized works and retiles with these methods:
- clicking the dock preview with the "Minimize windows into application icon" setting disabled in System Preferences
- bringing it back from HyperDock

Doesn't work with these methods:
- bringing it back with HyperSwitch
- using the right click menu from the dock icon

Genie effect is still wonky as well.

**Comment by matthewdias** [comment] 2016-03-22 23:46
Any new info on CGSSpaceDestroy?

**Comment by koekeishiya** [comment] 2016-03-23 00:08
It does exist, however it doesn't fully delete the space. It does delete it, as in make it useless. However, it is still there, but as a black screen.

**Comment by cHoco** [comment] 2016-03-27 20:54
Another use case that has been bugging me is when you maximise a window (using native OS X fullscreen) and then unmaximise it the window tree isn't updated.
Since it's detected as a space transition it should be possible to detect this and update window tree?

**Comment by koekeishiya** [comment] 2016-03-27 22:29
> Since it's detected as a space transition it should be possible to detect this and update window tree?

This should be doable by making a case for transitioning from an unmanaged space, to a managed space, and just force a call to UpdateWindowTree();

**Comment by koekeishiya** [comment] 2016-04-09 01:50
> Another use case that has been bugging me is when you maximise a window (using native OS X fullscreen) and then unmaximise it the window tree isn't updated.
Since it's detected as a space transition it should be possible to detect this and update window tree?

Fixed on master.

**Comment by matthewdias** [comment] 2016-04-09 09:02
As far as I can tell, everything from this issue has been implemented, and it all tests out. Works great, thanks! I think this one can be closed out now.

**Comment by koekeishiya** [comment] 2016-04-09 11:51
I remember you mentioned earlier that a you'd like a way to move to the `previous active space and not just `left | right`. I believe this can be achieved as well, and will look into keeping a full history per display.

Gonna close this issue for now then.

**Closed by koekeishiya** 2016-04-09 11:51 UTC
Labels: enhancement, maybe

**Comment by koekeishiya** [comment] 2016-04-09 12:51
> I believe this can be achieved as well, and will look into keeping a full history per display.

Implemented in latest commit on master. `kwmc window -m space previous` and `kwmc space -f previous`.

The space history for a display is stored as a stack and this command can be repeated til the stack empties.

**Comment by matthewdias** [comment] 2016-04-09 17:32
nice!

**Comment by matthewdias** [comment] 2016-04-09 17:41
mm its not working for me

**Comment by koekeishiya** [comment] 2016-04-09 17:53
There is a problem currently where moving a window to a different space with Kwm does not add that space to the history. Switching spaces using gestures or OSX hotkeys works fine for me though.
Does this command perform a space transition if run from a terminal? `kwmc space -f 2`
If not, try remove accessiblity permissions and reenable it.

**Comment by matthewdias** [comment] 2016-04-09 17:57
doesn't trigger the transition, even after removing and reenabling in accessibility settings

**Comment by koekeishiya** [comment] 2016-04-09 18:00
Hmm I really have no idea. It works just fine for me.

**Comment by koekeishiya** [comment] 2016-04-09 23:50
> doesn't trigger the transition, even after removing and reenabling in accessibility settings

The same thing randomly started happening to me, I'm really confused right now.
