### ISSUE TITLE
Better support for dual GPUs setups

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#323] opened 2016-04-19 11:19 UTC
This has been bugging me **a lot** in the last couple of days. 
Basically on Macs with dual GPUs, one is the integrated graphic card in the cpu and the other is the dedicated discrete chip, when OS X automatically switches from one to the other, kwm notices it as new display being added (and the old display being deleted) recreating the window tree from scratch and thus losing the current windows arrangements :(

**Comment by dominiklohmann** [comment] 2016-04-19 11:20
Duplicate of #123... it's been a while. Still bugging me as well.

**Comment by koekeishiya** [comment] 2016-04-19 11:22
I'm aware of this issue but do not have the hardware to work on it.

**Comment by cHoco** [comment] 2016-04-19 11:22
Ops, didn't notice it! I'll be investigating this and see if there's something I can do!

**Comment by chrishoage** [comment] 2016-04-19 16:12
This issue exists for 4k monitors as well. Apples solution to 4k monitors not waking from sleep is to add and remove the display (with these strange "fake" transient displays) until the monitor wakes up. 

Better support for when a monitor is added and removed would be greatly appreciated. @cHoco if you need test subjects ping me and I can run any patches you give me.

**Comment by chrishoage** [comment] 2016-04-19 16:14
More history in #161

**Comment by cHoco** [comment] 2016-04-19 18:46
Can someone try out this diff diff and tell me if it works, if not what doesn't work, and post the logs. The diff is full of useless code but I was getting frustrated and didn't really clean up after every failed attempt XD

Here's the diff: https://gist.github.com/cHoco/eb429aa9d2134cbebada483373cfdd9f/raw

**Comment by chrishoage** [comment] 2016-04-19 18:55
4k monitor wake from sleep still broken. About to test automatic display switching (need to unhook my external. 

```
Local Daemon is now running..
DisplayID 441231622 has index 0
DisplayID 69733314 has index 1
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
Application was activated through cmd+tab or the dock!
Display reconfiguration
Display reconfiguration
Display reconfiguration
I ALREADY HAVE THIS DISPLAY U WANNA REMOVE
UPDATING EXISTING SCREEN
DisplayID 69733314 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
GiveFocusToScreen() 0: Space transition ended 3 -> 3
Uninitialized Screen
Display reconfiguration
Display 69733314 changed resolution
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
Display reconfiguration
Display reconfiguration
Display reconfiguration
I ALREADY HAVE THIS DISPLAY YOU WANNA ADD
Adding NEw SCREEN
DisplayID 69733314 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
GiveFocusToScreen() 0: Space transition ended 3 -> 103
Uninitialized Screen
Display reconfiguration
UPDATING EXISTING SCREEN
DisplayID 69733314 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
Display reconfiguration
Display reconfiguration
Display reconfiguration
MMMMMM WHAT?!?
Display reconfiguration
I ALREADY HAVE THIS DISPLAY U WANNA REMOVE
UPDATING EXISTING SCREEN
DisplayID 441231622 has index 0 and ID: 4268EF99-6620-8CD4-A0E6-EFD08D4D5365
UPDATING EXISTING SCREEN
DisplayID 69733314 has index 1 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
GiveFocusToScreen() 0: Space transition ended 103 -> 3
Populated Screen Key/Mouse Focus
CreateWindowNodeTree() Create Space 103
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window:  3860,1198
UpdateActiveScreen() Active Display Changed
GiveFocusToScreen() 1: Space transition ended 3 -> 103
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window:  3860,1198
ShouldMonocleTreeUpdate() Add Window
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: Slack 3860,1198
ShouldMonocleTreeUpdate() Add Window
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: iTunes 3860,1198
Display reconfiguration
Display reconfiguration
space changed on monitor: 0
Display reconfiguration
MMMMMM WHAT?!?
Display reconfiguration
Display 69733314 changed resolution
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
CreateWindowNodeTree() Create Space 103
Restarting Event Tap
GiveFocusToScreen() 0: Space transition ended 103 -> 3
^C
```

**Comment by chrishoage** [comment] 2016-04-19 18:59
It DOES appear to work when unchecking and rechecking allow GPU switching 

```
Local Daemon is now running..
DisplayID 2077750333 has index 0
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: Energy Saver 377,53
Display reconfiguration
Display reconfiguration
Display reconfiguration
I ALREADY HAVE THIS DISPLAY YOU WANNA ADD
UPDATING EXISTING SCREEN
DisplayID 69733314 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
Display reconfiguration
I ALREADY HAVE THIS DISPLAY U WANNA REMOVE
UPDATING EXISTING SCREEN
DisplayID 69733314 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
Display reconfiguration
Display reconfiguration
Display reconfiguration
I ALREADY HAVE THIS DISPLAY YOU WANNA ADD
UPDATING EXISTING SCREEN
DisplayID 2077750333 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
Display reconfiguration
I ALREADY HAVE THIS DISPLAY U WANNA REMOVE
UPDATING EXISTING SCREEN
DisplayID 2077750333 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
^C
```

I am seeing odd behavior with `standby-on-float` but am unsure if that has anything to do with your diff @cHoco 

Let me know if you need more info.

**Comment by chrishoage** [comment] 2016-04-19 19:03
The `standby-on-float` issues I am seeing are only present in your diff @cHoco. When I reverted back to master the issue went away. 

Issue: 

Open an application set to Float (I have System Prefs set up like this). 
Click on a background app. 
Notice `focus-follows-mouse` is not triggered, and the `focus-border` is gone and never updates. 

On master I can't reproduce this behavior.

**Comment by cHoco** [comment] 2016-04-19 19:13
Whats the current behaviour with 4k display? And what would be your expected behaviour?

**Comment by chrishoage** [comment] 2016-04-19 19:18
There is a lot of history in #108

Basically since 10.11.3 when a Mac has a 4k monitor that goes to sleep in order to wake it up and "adds and removes" the display until the display wakes from sleep. Due to the displays being added and removed the BSP tree is massively broken when OS X is done doing its "connect disconnect dance". 

It creates these fake "transient" displays that don't actually exist (I only have 2 displays and 3 ids show up). 

The expected behavior is the Tree's on each display is preserved when going from a sleep state to a wake state. 

Right now the trees get reset, sometimes to wrong dimensions. 

This is a very similar issue to #161

Please let me know if there is any more info you need.

**Comment by koekeishiya** [comment] 2016-04-19 20:59
@cHoco Thanks for looking into all this crazy monitor stuff. Very much appreciated.

**Comment by cHoco** [comment] 2016-04-19 21:01
Unfortunately I don't have a secondary monitor to test with until tomorrow so I'm practically basing my assumptions on your logs for now, can you test this diff and report the logs? https://gist.github.com/cHoco/f956aabe8ab8f6a6dad285175b2f5d72/raw

This will portably crash kwm but the logs should be useful anyway.

**Comment by chrishoage** [comment] 2016-04-19 21:04
It did indeed crash kwm. Logs: 

```
Local Daemon is now running..
DISPLAYPORT 16135
DisplayID 441231622 has index 0 and ID: 4268EF99-6620-8CD4-A0E6-EFD08D4D5365
DISPLAYPORT 16423
DisplayID 69733314 has index 1 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: Better support for dual GPUs setups · Issue #323 · koekeishiya/kwm 1930,1077
Application was activated through cmd+tab or the dock!
Display reconfiguration
Display reconfiguration
Display reconfiguration
NUMBER OF DISPLAYS: 1
Apr 19 14:03:27  kwm[59058] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Apr 19 14:03:27  kwm[59058] <Error>: CGSServiceForDisplayNumber: Invalid display 0x1a4ca906
DISPLAYPORT 0
DISCONNECTED
Display 441231622 is asleep!
UPDATING EXISTING SCREEN
DisplayID 69733314 has index 0 and ID: 1FBF2F7F-57EC-56E5-521F-556A305D1A61
GIVING FOCUS TO SCREEN
GiveFocusToScreen() 0: Space transition ended 3 -> 3
Uninitialized Screen
Display reconfiguration
Display 69733314 changed resolution
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
Display reconfiguration
Display reconfiguration
Display reconfiguration
NUMBER OF DISPLAYS: 1
DISPLAYPORT 25519
[1]    59058 segmentation fault  ./bin/kwm
```

**Comment by cHoco** [comment] 2016-04-19 22:46
@chrishoage Can you also post the relative CrashReport? If you open Console you should have it somewhere, so I can see the backtrace of the various threads. 

Ok, some infos I gathered:

When switching GPUs the `Identifier` returned  by `CGSCopyBestManagedDisplayForRect` doesn't change, so I though that it would be perfect to check if the added/removed display in the callback has the same Identifier and if so, just update the DisplayID for that Identifier without resetting the window tree.

This works, but it doesn't covert all cases, for example when if I connect an external display and close my MacBook the logic implemented above doesn't work, because CGSCopyBestManagedDisplayForRect returns the external display since it doesn't consider the asleep monitor as valid anymore.... 

So I thought of other methods to uniquely identify a display and found `CGDisplaySerialNumber`, but obviously this function always returns 0 👎 
But fortunately IOKit comes to the rescue, by opening the IO service port relative to a display we can extract some useful infos like the EDID key, a blob of data that should uniquely identify a display. Since it's raw data I decided to hash it for easier comparison. This seems to work, tomorrow I hope to clean up useless changes in the diff and push a pull to support dual GPU, then I'll start checking out whats the deal with external displays.

**Comment by chrishoage** [comment] 2016-04-19 22:49
@cHoco https://gist.github.com/chrishoage/47f3ed9364e6aaedd3398a07d948a766

**Comment by cHoco** [comment] 2016-04-19 22:56
@chrishoage Thanks, if you can try also this diff https://gist.github.com/cHoco/c34be80f2b80efce45292685aac2c46a/raw and post logs it'd be cool :)

**Comment by chrishoage** [comment] 2016-04-19 23:02
@cHoco Logs and Crash report - https://gist.github.com/chrishoage/0c134a8df583eca79683161a74eb7378

**Comment by cHoco** [comment] 2016-04-19 23:08
Super strange that it's crashing there, last try for the night XD https://gist.github.com/cHoco/a0e3e357bab31dc294b93a4a9333d73f/raw

**Comment by chrishoage** [comment] 2016-04-19 23:13
@cHoco No crash this time, but all windows that were in a BSP tree on my external ended up on my laptop display which was in monocle mode. They all resized correctly though. 

https://gist.github.com/chrishoage/cdb568979d191a4b31c62cf6e7cf4a8b

**Comment by koekeishiya** [comment] 2016-04-19 23:20
> No crash this time, but all windows that were in a BSP tree on my external ended up on my laptop display which was in monocle mode.

This will happen for windows that are detected on the space of an unfocused monitor, but are neither floating nor tiled, and that space has been initialized (Space->Initialized has been set).

I have not looked through the diff yet, but it seems that the state of the space on a display has not been recovered properly.

> They all resized correctly though. 

This is not related to any of the above changes, but due to changes I made a week ago or so regarding how Kwm looks at windows and compares it to windows currently in the window-tree.

**Comment by chrishoage** [comment] 2016-04-19 23:25
Ah, my all "They all resized correctly though" comment was in reference to how before when my laptop display returned from sleep the windows that were previously in monocle mode before were in a "monitor not initialized" state until I used the mouse to "initialize" the monitor. 

With this diff, I did not have to initialize the monitor, the windows were already in monocle mode and the correct size.

**Comment by koekeishiya** [comment] 2016-04-19 23:26
> Ah, my all "They all resized correctly though" comment was in reference to how before when my laptop display returned from sleep the windows that were previously in monocle mode before were in a "monitor not initialized" state until I used the mouse to "initialize" the monitor. 

Ah right, that's great progress then.

**Comment by cHoco** [comment] 2016-04-21 12:48
I started fresh and slightly changed approach, would you mind test this patch and report back? thank you https://gist.github.com/cHoco/472fcb46d1a65235c2357c8ebd589e93/raw

**Comment by cHoco** [comment] 2016-04-21 13:19
Sorry for double posting, but ignore the previous one and try this one that has more logging, thanks 👍

**Comment by chrishoage** [comment] 2016-04-21 16:23
>  try this one that has more logging

@cHoco just so I make sure Im trying the right thing: Did you update your previous gist or forget to link the new one?

**Comment by cHoco** [comment] 2016-04-21 16:24
@chrishoage I forgot to add it XD Here it is https://gist.github.com/cHoco/0ed0418a24f6ab60009566677c1a20df

**Comment by chrishoage** [comment] 2016-04-21 16:43
The first time I tried this it _appeared_ it worked perfectly, but I was not able to reproduce my success. 

https://gist.github.com/chrishoage/72a0ac049b5a26e58bc6c26bc606bc7d

I have included logs. 

What happens is everything ends up on my laptop display in a broken (as in some windows are the incorrect size) BSP tree. 

I also got these logged to STD Error

```
Apr 21 09:40:38  kwm[51765] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Apr 21 09:40:38  kwm[51765] <Error>: CGSCopyDisplayUUID: Invalid display 0x1a4ca906
```

**Comment by chrishoage** [comment] 2016-04-21 16:45
Hold on I might have forgotten to re-build. (Sorry early and coffee still kicking in) Let me try this all again.

**Comment by chrishoage** [comment] 2016-04-21 16:51
Ok, looks like I'm not an idiot. Reapplied patch and rebuilt, same result. 

```
Apr 21 09:50:47  kwm[55631] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Apr 21 09:50:47  kwm[55631] <Error>: CGSCopyDisplayUUID: Invalid display 0x1a4ca906
```

[display-log.txt](https://github.com/koekeishiya/kwm/files/230381/display-log.txt)

**Comment by cHoco** [comment] 2016-04-21 16:58
@chrishoage From the logs you're using my patch so you did good :D

Right now GPU switching should be ok (if @dominiklohmann also had time trying to see if that part works), the external display issue is harder because I personally can't test first hand so I'm going with only the logs ahah
Just a couple of questions, when the display is starting up if you DON'T have kwm running whats the behaviour? Are the windows, that were in that monitor, temporary moved to the *awake* display?  Actually, do you put all display to sleep or only the 4k one?

**Comment by cHoco** [comment] 2016-04-21 17:13
@chrishoage Please try this one, included small change https://gist.github.com/cHoco/776a8bb86dc9e1b405d565aac3342fc5/raw

**Comment by chrishoage** [comment] 2016-04-21 17:21
> Are the windows, that were in that monitor, temporary moved to the awake display?

So, I normally run with "Screen Lock" enabled, but I was curious so I disabled it. 

Some _strange ass shit_ happens when I watch OSX do it's display disconnect-reconnect dance. As you deduced the windows _are_ temporary moved to the awake display, then when the external display finally gets forced awake from the disconnect/reconnect dance it does, OS X then moves the windows were temporary moved BACK to the external display. 

Just to show you how utterly fucking _stupid_ this behavior is I have recorded a video of how OS X wakes the display. Keep in mind that this is with NO KWM. Only OS X managing the windows. 

https://www.dropbox.com/s/xv1qas9gdjxvbuc/Video%20Apr%2021%2C%2010%2009%2049%20AM.mov?dl=0

I have tried that patch, and it pretty much works! All the windows that were previously on my external end back up on my external. They don't end up in the same spot, but this is HUGE progress. 

What I normally do is wake my external display first, _then_ wake my computer. And this works fine. Sometimes I forget to wake my external and kwm flips out during the disconnect-reconnect process shown in the video. 

Your patch helps kwm handle the situation more gracefully

**Comment by koekeishiya** [comment] 2016-04-21 17:29
> I have tried that patch, and it pretty much works! All the windows that were previously on my external end back up on my external. They don't end up in the same spot, but this is HUGE progress. 

I believe the internal id of spaces of a display is during the `display-dance` process, which could be the cause of it. It seems like @cHoco has been able to maintain the state of the displays. To confirm this, you could log the id of all spaces in the DisplayMap->Spaces map both before and after the above process.

**Comment by matthewdias** [comment] 2016-04-21 19:07
Ok, so doing some testing with graphics switching. The system apparently uses 2 different 'displays' for each gpu. Here, `69731906` is discrete graphics, and `2077751741` is integrated. On switch from discrete to integrated:
```
New display detected! DisplayID: 2077751741 Index: 1
DisplayID 2077751741 has index 0
Display has been removed! DisplayID: 69731906
DisplayID 2077751741 has index 0
GiveFocusToScreen() 0: Space transition ended 3 -> 3
Uninitialized Screen
CreateWindowNodeTree() Create Space 3
```

Switching back does the same thing in reverse with the same display IDs.

Results with the latest patch:
https://gist.github.com/739518d60c8ae81b1a782951daa822f4

**Comment by cHoco** [comment] 2016-04-21 19:49
@matthewdias  Is it maintaining the window tree while switching GPUs?

I cleaned up the code a bit and fixed a crash, functionality should be the same as previous patch, anyone who has some time please try this https://gist.github.com/cHoco/14c6143ce94f9c460f74079e6918f458/raw and post logs

**Comment by cHoco** [comment] 2016-04-21 19:52
Actually use this version https://gist.github.com/cHoco/6d9337b9fd2fe75bab801fe2dc57bfb5/raw rebase on master

**Comment by matthewdias** [comment] 2016-04-21 20:06
hmm, was mucking around with branches and i think i confused it. 
```
<unknown>:0: error: PCH was compiled with module cache path '/var/folders/p6/glgbxzz96hv5pd7xgzqyn4jr0000gn/C/org.llvm.clang.Matthew/ModuleCache/P6LLBOI77PIF', but the path is currently '/var/folders/p6/glgbxzz96hv5pd7xgzqyn4jr0000gn/C/org.llvm.clang.matthew/ModuleCache/P6LLBOI77PIF'
<unknown>:0: error: missing required module 'SwiftShims'
make: *** [obj/kwm-overlay/kwm-overlay.o] Error 1
```

`sh: /Users/Matthew/Dropbox/Development/osx/kwm/bin/kwm-overlay: No such file or directory`
kwm crashes.

**Comment by cHoco** [comment] 2016-04-21 20:10
No idea what that error could mean, didn't event touch kwm-overlay source in this patch. Maybe try a hard reset?

Fixed and issue when building release version: https://gist.github.com/cHoco/16e17df6c569cc646e104204fcc9dd02/raw

**Comment by matthewdias** [comment] 2016-04-21 20:11
Ok fixed my issue but in latest diff: `kwm/display.cpp:98:13: error: expected expression
            else`

**Comment by chrishoage** [comment] 2016-04-21 20:12
It actually seems to work from me. 

I did have a crash when OS X had to "try really hard" to wake up the display (doing the disconnect-reconnect thing a whole lot)

I'm trying to repo the crash, will post logs and crash report when I can. In the meantime here are logs from it working successfully! Everything stays put! 

[display-log-works.txt](https://github.com/koekeishiya/kwm/files/230650/display-log-works.txt)

**Comment by cHoco** [comment] 2016-04-21 20:19
@matthewdias Ops, silly mistake https://gist.github.com/cHoco/574a7e0d1e58aa021180665bb34260db/raw

**Comment by matthewdias** [comment] 2016-04-21 20:24
All good, tree is preserved.

https://gist.github.com/matthewdias/9592d0a81fe725f57994acd5207b2b25

**Comment by dominiklohmann** [comment] 2016-04-22 10:12
Just tried the patch out, it's working so far when switching between the GPUs. Awesome work!

**Comment by koekeishiya** [comment] 2016-04-22 13:20
Merged into master, thanks!

**Closed** 2016-04-22 16:29 UTC
Labels: bug, fixed@master

**Comment by cHoco** [comment] 2016-06-20 20:09
With the rewrite two issue regressed for me:

1. GPU change resets all spaces trees
2. Display resolution change break split-mode if it was changed.

**Comment by koekeishiya** [comment] 2016-06-20 20:20
> 1. GPU change resets all spaces trees

See note at top of `kwm/window.cpp` for reason behind this.

> 2. Display resolution change break split-mode if it was changed.

Not sure why this happens, will investigate.

**Comment by dominiklohmann** [comment] 2016-06-20 20:25
> See note at top of `kwm/window.cpp` for reason behind this.

``` 
/* TODO(koekeishiya): std::map cannot properly compare CFStringRefs. Consider writing
                      our own map type or switch back to CGSSpaceID. Using a CGSSpaceID
                      would require a remap between old and new CGSSpaceIDs in certain cases.
                      Is there a better alternative (?) */
```

You should be able to write a wrapper around CFStringRef to use with std::map that uses custom comparison operators.

**Comment by koekeishiya** [comment] 2016-06-20 20:33
> You should be able to write a wrapper around CFStringRef to use with std::map that uses custom comparison operators. 

That is a possible solution, although I'd rather write my own, as I'm not a fan of the stdlib for various reasons. I'd like to step away from using it alltogether at some point.

**Comment by koekeishiya** [comment] 2016-07-05 13:28
> With the rewrite two issue regressed for me:

>    GPU change resets all spaces trees
>    Display resolution change break split-mode if it was changed.

Both of these should be fixed on the latest master.
