### ISSUE TITLE
"Phantom" windows messing up layout

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#401] opened 2016-06-25 08:47 UTC
This is such a strange issue, but it happens almost twice a day, so it isn't really isolated. Basically sometimes windows retile themselves  in a space like there were additional windows there. For example a window that would take full space is retiled at half of it seemingly because there's another window there. Adding another window just keep tiling like there's this phantom window. I have to switch spaces usually to let kwm notice this.

I really don't know how to reproduce it, the only thing I can think is that it usually happens after the computer has been in standby, but not always as soon I wake it up.

**Comment by dominiklohmann** [comment] 2016-06-25 08:52
I experienced the same issue when moving windows to another space using Mission Control and then returning to the space I moved the window away from. 

For example, I can reliably reproduce this when having any amount of windows on space A, moving any amount of them using Mission Control to space B, then returning to space A (never actually rebuilding the window tree for space B). The only thing short of restarting Kwm that fixes the window tree on space A is moving to space B and back in this case.

**Comment by cHoco** [comment] 2016-06-25 08:56
@dominiklohmann I'm pretty sure moving window between spaces without using kwm own command isn't supported, especially in this version since we just react to notifications.

**Comment by dominiklohmann** [comment] 2016-06-25 09:50
I know, just wanted to say how I can reliably produce such "phantom" windows.

**Comment by colonelk1** [comment] 2016-06-25 16:48
The same happens to me --- moving spaces with mission control. Didn't happen prior to the update to 3.0.

**Comment by trifle** [comment] 2016-06-27 13:47
By the way, this also happens to me when hiding windows (cmd-h). After hiding an app, the screen stays divided as if it were still active.

**Comment by thonixx** [comment] 2016-06-28 10:10
And I can tell that the same happens with multiple displays when having an app in fullscreen on one of the displays and then moving the cursor away to the display where kwm is tiling the non-fullscreen apps and then it retiles the windows (even the one in fullscreen and the fullscreen app then takes only a part of its screen size).

**Comment by koekeishiya** [comment] 2016-07-01 12:43
> By the way, this also happens to me when hiding windows (cmd-h). After hiding an app, the screen stays divided as if it were still active.

Hiding applications is not supported, see #394.

> And I can tell that the same happens with multiple displays when having an app in fullscreen on one of the displays and then moving the cursor away to the display where kwm is tiling the non-fullscreen apps and then it retiles the windows (even the one in fullscreen and the fullscreen app then takes only a part of its screen size).

OSX Fullscreen mode is not supported, see #390 for manual workaround.

> The same happens to me --- moving spaces with mission control.

As cHoco said, this is no longer supported as Kwm only listens to notifications (instead of polling as it did in previous versions), use the builtin move command.

**Comment by trifle** [comment] 2016-07-01 12:49
Thanks for the clarification. I'm all for simple and clean implementations so I guess I'll stop hiding windows. As far as I'm concerned this issue can be closed.

**Comment by sebinsua** [comment] 2016-07-03 18:03
I am getting this quite frequently, too. I don't think I'm doing anything special though, just moving between Atom, iTerm2 and Firefox using the mouse. I can't describe the exact process that causes the problem yet...

**Comment by nicoNaN** [comment] 2016-07-22 18:52
This happens to me regularly while using Kwm and I don't know exactly how to reproduce. However, it seems possibly related to having other programs open that do not have a window open. For example, having iTunes open but with the window closed, then quitting iTunes, sometimes will cause the "phantom" window to close.

**Comment by nicoNaN** [comment] 2016-07-26 15:23
As an update: noticed this happens particularly often when switching between spaces. Upon switching to a space with a window in it, it will randomly shrink to a very small size - about 1/6 of screen size.

**Comment by bjeanes** [comment] 2016-07-26 22:39
@nicoNaN I find that I am regularly "restarting" kwm 3-5x per day for this reason. The only instance I can usually reproduce is as you described, with Preview.app. Opening an image or PDF then _closing_ that window will leave a space in place (at least, sometimes). Quitting Preview releases the ghost window's claim on that tile and the layout retiles correctly. However, it does happen to me in other cases too that are harder to reproduce and seemingly random. I think Slack causes some issues too, but they might be different (like the window "sticking" and travelling with me whenever I visit another OS X Space and leaving its ghost window on the previous layout with no obvious way to "unstick" it).

**Comment by koekeishiya** [comment] 2016-07-26 23:42
> I can usually reproduce is as you described, with Preview.app. Opening an image or PDF then closing that window will leave a space in place (at least, sometimes).

This specific instance is now fixed on the current master (for me, at least).

**Comment by bjeanes** [comment] 2016-07-27 01:00
@koekeishiya I thought it'd be something like that.

**Comment by cHoco** [comment] 2016-07-27 07:09
It really happens a lot with Preview. But from the debug log the notification is received.
Here's my log:

```
AXEvent_WindowDestroyed: Preview - Modern_Memory_Safety_In_C_CPP.pdf (page 19 of 290)
GetScratchpadSlotOfWindow() Modern_Memory_Safety_In_C_CPP.pdf (page 19 of 290) -1
```
And I still end up with a tree slot taken :(

**Comment by jantoebes** [comment] 2016-08-09 07:12
This issue also appears when sending a mail via the mailapp. Is there a workaround for this issue? So at least I dont have any 'ghost' windows?

**Comment by Drin** [comment] 2016-08-09 21:06
I get these issues a lot just by switching workspaces. I likely have a slightly modified workflow, but I typically have iTerm open and chrome.

I often open new iTerm windows using cmd + n (I assume this is supported) and it usually works well, but can get confused when i have iTerm windows on multiple spaces or multiple displays. Often times when I switch workspaces on one display, windows on a previous workspace (same display) will tile incorrectly (as mentioned in this thread). And once this happens to one workspace, the issue then propagates to other workspaces and I find myself restarting kwm via brew services (I assume this is okay?).

I also often open a new tab in chrome, and will drag the tab out into it's own window using the mouse, and then I will switch it to another display, and then fullscreen a video. In this case, I use the mouse only to make a tab into a window, and to fullscreen the video. I use kwm hotkey to then switch the window to a different display. The tab -> window works fine, but fullscreen of a video makes things go horribly wrong, and the display will turn black, with the video rendering out of bounds of the display, and kwm attaches the video's window to my other window containing my other tabs (seemingly). I'm not sure if the root cause for this is similar to phantom windows or if full screening a video is unsupported, so I thought I would mention it here.

I can try and investigate this more later, and if you'd prefer I mention this in a different, or new, issue, let me know!

Thanks!

**Comment by koekeishiya** [comment] 2016-08-10 18:44
I only have this problem with preview. Are there other applications where this is happening as frequently? Keep in mind the situations I mentioned in my post above.

**Comment by bjeanes** [comment] 2016-08-11 00:00
I wonder what could be different about our setups such that I have issues with Preview almost daily (I'd say ~70% of Preview windows get ghosted)... Is there any debug information or config I can give you that might help isolate the problem?

**Comment by cHoco** [comment] 2016-08-11 00:52
I think that there are two different issues here, one is when an application seemingly doesn't send a notification when a window is destroyed. Not sure whose fault is it in this case, but it is usually easily solved by switching between spaces.
Then there's another issue that instead really messes up the space that is caused by a window getting added to a space more than once. I'm not sure how this happens but I confirmed that this is the case because I added this small change and I saw the error popup once.

``` diff
diff --git a/kwm/window.cpp b/kwm/window.cpp
index 96335f8..130d64a 100644
--- a/kwm/window.cpp
+++ b/kwm/window.cpp
@@ -999,12 +999,18 @@ void ResetWindowNodeTree(ax_display *Display, space_tiling_option Mode)
 void AddWindowToNodeTree(ax_display *Display, uint32_t WindowID)
 {
     space_info *SpaceInfo = &WindowTree[Display->Space->Identifier];
-    if(!SpaceInfo->RootNode)
-        CreateWindowNodeTree(Display);
-    else if(SpaceInfo->Settings.Mode == SpaceModeBSP)
-        AddWindowToBSPTree(Display, SpaceInfo, WindowID);
-    else if(SpaceInfo->Settings.Mode == SpaceModeMonocle)
-        AddWindowToMonocleTree(Display, SpaceInfo, WindowID);
+    std::vector<uint32_t> WindowIDsInTree = GetAllWindowIDsInTree(SpaceInfo);
+    if (std::find(WindowIDsInTree.begin(), WindowIDsInTree.end(), WindowID) != WindowIDsInTree.end()) {
+        DEBUG("ERROR - AddWindowToNodeTree: WindowID is already in window tree");
+        return;
+    } else {
+        if(!SpaceInfo->RootNode)
+            CreateWindowNodeTree(Display);
+        else if(SpaceInfo->Settings.Mode == SpaceModeBSP)
+            AddWindowToBSPTree(Display, SpaceInfo, WindowID);
+        else if(SpaceInfo->Settings.Mode == SpaceModeMonocle)
+            AddWindowToMonocleTree(Display, SpaceInfo, WindowID);
+    }
 }
 
 void RemoveWindowFromNodeTree(ax_display *Display, uint32_t WindowID)
```
the next step is checking when that happens, since it is usually after a space changed notification, I'll probably get around that tomorrow.

**Comment by koekeishiya** [comment] 2016-08-11 11:50
So moving windows using mission control is once again somewhat possible. It will be tiled properly on the target space when it gains focus, but it does leave an empty slot on the space the window was on. This can be resolved by performing a space transition.

Native OSX fullscreen now has better support as well.  Making a window fullscreen, and non-fullscreen again without the space of the window being visited, will  cause the window to keep its tiled slot. If the space is visited while the window is still in fullscreen, the slot will be freed.
When the window becomes non-fullscreen again, it will be tiled according to the default position in the tree.


All phantom windows should in theory be removed after performing a space transition, as this causes a tree rebalance.

**Comment by jantoebes** [comment] 2016-08-17 05:36
Is there a possibility for a keycommand to do a tree rebalance? So you are able to clean up ghost windows without performing a space transition?

**Comment by bjeanes** [comment] 2016-08-17 07:25
@jantoebes I constantly restart kwm with the built-in shortcut to quit kwm (as `launchd` just automatically restarts it). However, it kinda sucks because I'm doing this on average 3-4 times a day and then I have to re-organize my windows a bit the way I want them :(

**Comment by koekeishiya** [comment] 2016-08-17 07:42
The following patch can be used as a fix for now. It is far from optimal and so I do not want to push this as an actual fix, although it should solve the problem.

https://gist.github.com/koekeishiya/b04937eed49331cef6c13712584018e1

**Comment by Drin** [comment] 2016-08-17 18:12
@koekeishiya fyi, I'm not sure if it's related or actually a different bug. But I often have a separate browser window and the interactions with it and pycharm when switching workspaces seems to sometimes trigger odities.

Steps (occurred once as far as I know, not sure how to reproduce):

1) I had a chrome window with 3 tabs on laptop monitor in its own space, a fullscreen'd stream from nbc's olympic stream had just finished and it closed itself (going back to normal size), pycharm was on  my external display in its own workspace.
2) I switched to workspace with pycharm on it, my browser window on my laptop display went to the same display as pycharm and they then split the window into 2 parts vertically (looked standard, except switching displays happened due to some bug).
3) I use the kwm hotkey to switch browser window to laptop display, pycharm resizes to fill external display, but now browser window takes only half of my laptop display, as if there is another window next to it.
4) use kwm hotkey to move browser window to an adjacent space on my laptop display, then switch to it, and it fills the whole display as expected
5) use kwm hotkey to move browser window to original space on my laptop display, then switch to it, and it still only fills half the screen (though this time it's the right side instead of the left side).

I haven't updated since my previous post, so I'll update sometime today and if it happens again I can post here. I just wanted to provide you with an example of how this happens for me for processes that are not preview. This also occurs relatively frequently with iTerm2 windows, though erroneous display switching only happens with fullscreen videos from nbc's site (perhaps some oddity in their implementation if it's flash-based or something of the sort?).

**Comment by koekeishiya** [comment] 2016-08-17 18:32
> perhaps the above is an example of something adding itself to the space more than once.

This does sound like a separate issue, however it should no longer happen in v3.0.7.

See the patch I posted above for a temporary fix to the main issue, if it becomes too annoying, while I try to figure out a better solution.

**Comment by jantoebes** [comment] 2016-08-18 07:18
Ok, 

for me it would be enough if i can attach a key-command to rebalancing.

So that means if there is a phantom window I don't have to restart KWM or switch panes to activate a rebalance, but just enter a hotkey and the problem is solved.

That would make it for me much more acceptable :-)

Btw @koekeishiya I think you're doing an amazing job with this tiling manager!

**Comment by thonixx** [comment] 2016-08-18 11:24
I could reproduce one of the phantom window issues. First to mention that I tried the patch https://gist.github.com/koekeishiya/b04937eed49331cef6c13712584018e1 but it does not work for my issue.

I reproduce it as follows with branch tag 0.3.7:
1. Having 2 external monitors plugged in
2. Opening any application
3. Opening a second window from the same application
4. Drag the window to the other monitor

What I expect:
Both windows take the whole space on both monitors.

What happens instead:
The window I have dragged takes the whole monitor (which was empty before) and the only window left on the previous monitor only consumes half of the space. With resizing it jumps just back into his half-monitor position.

**Comment by koekeishiya** [comment] 2016-08-18 11:34
Dragging windows will never be "officially" supported, because it is not something that I can reliably detect. I have added some code that should help alleviate these issues somewhat, but it is not something that can be fixed.

I would recommend using Kwm as you would any tiling wm for the x-windowing system, where if you want to drag something, make it float. If you just want to move windows, create suitable binds or this.

**Comment by bjeanes** [comment] 2016-08-19 02:08
I'm curious about how I can better debug this situation. Today I'm running with multiple spaces (which I only do when I have no external bigger monitor) and I've suddenly got an unexplained ghost window on exactly one of my Spaces. Switching spaces does not re-layout the screen. I have no idea what KWM thinks is there. Is it possible to access debug information about what KWM thinks is occupying that slot? All the spaces are BSP and I never had anything (to my knowledge) on that space except for Slack.

![screen shot 2016-08-19 at 12 04 22 pm](https://cloud.githubusercontent.com/assets/2560/17796635/653e6ddc-6605-11e6-8141-86cd1311c24c.png)

**Comment by bjeanes** [comment] 2016-08-19 02:10
Ugh ignore that, it was a _hidden_ window. Still, it would be helpful to know if kwm does have enough information to display what it expects to be in that phantom slot, as I am getting phantom slots often (which usually have nothing to do with hiding applications, because I rarely do that other than by accident and know to look for it as a cause of these problems)

**Comment by thonixx** [comment] 2016-08-19 08:49
@koekeishiya I never got the keybindings working. Either I am too dumb or something is wrong with them. So I drag the windows, kill kwm and it works again as expected.

**Comment by koekeishiya** [comment] 2016-08-19 10:18
> I never got the keybindings working. Either I am too dumb or something is wrong with them. So I drag the windows, kill kwm and it works again as expected.

If no keybindings work at all, you probably have to disable 'secure keyboard entry' found in terminal settings (even if it is listed there, it applies system-wide).

> Ugh ignore that, it was a hidden window. Still, it would be helpful to know if kwm does have enough information to display what it expects to be in that phantom slot, 

There is currently no way to check this without running inside a debugger.

> have nothing to do with hiding applications

Hiding appllications have been implemented on master.

**Comment by thonixx** [comment] 2016-08-22 11:25
@koekeishiya I  never enabled Secure Keyboard Entry and therefore it is still disabled. But still not working at all. I just be ok with not using any shortcuts since the most important thing is ffm and tiling is not very important.

**Comment by koekeishiya** [comment] 2016-09-11 14:29
So I've been unable to reproduce this issue with `Preview`, `iTunes` and a few other applications at all, in version 3.1.3 (suspect the changes in #448 had something to do with it). 

The issue where a window would be tiled multiple times for the same space has also been fixed.
Show / hide applications is now supported.

I am gonna close this due to the fact that the information has been relativelt hard to process as there are symptomps for several different issues all garbled in here.

Freel free to create new issues if they don't overlap with #472 and #445

**Closed by koekeishiya** 2016-09-11 14:29 UTC
Labels: bug
