### ISSUE TITLE
Kwm: Could not start daemon..

### ISSUE THREAD

**Issue by escherize** [koekeishiya/kwm#9] opened 2015-12-22 14:29 UTC
Hello!

Found your project on HN, and getting ready to try something new besides Spectacle.

I expected to be able to close kwm, and re-open it, but was unable to do so, and greeted with the string in the title.

I used iTerm, gave it Accessibility access, copied kwmc onto my path and ran kwm from the directory it was built in.  Subsequently Killed it with Cmd+C, closed iTerm.

**Comment by koekeishiya** [comment] 2015-12-22 14:31
This issue might be caused by opening new iTerm windows when Kwm is running. Closing all iTerm windows should let you be able to start Kwm again. Basically Kwm uses port 3020 for it's daemon at this point, and new iTerm windows seem to be keeping this port locked.

Will look into it more in the future.

**Comment by escherize** [comment] 2015-12-22 14:51
Ahh.

Yes a reboot fixed it. I shall try killing all my iTerms next time.  Fabulous tool, thanks for putting it out.

**Comment by koekeishiya** [comment] 2015-12-26 13:53
This issue has now been fixed.

**Closed by koekeishiya** 2015-12-26 13:53 UTC
Labels: bug
