### ISSUE TITLE
Add keyboard shortcut to change current space without transition

### ISSUE THREAD

**Issue by mmmulani** [koekeishiya/kwm#304] opened 2016-04-11 17:37 UTC
This feature is heavily desired but currently don't have a way to do it without extreme bugginess.

**Comment by mmmulani** [comment] 2016-04-11 17:38
@koekeishiya what API were you using previously that ran into problem? CGSSetWorkspace or CGSSetWorkspaceWithTransition?

**Comment by mmmulani** [comment] 2016-04-11 17:43
oh interesting, maybe the API has changed to `CGXSetWorkspace` though there is also a `_XSetWorkspace`

**Comment by koekeishiya** [comment] 2016-04-11 17:48
Last time i checked, the above API's do not work anymore. The last one I tried was `CGSManagedDisplaySetCurrentSpace(CGSConnectionID cid, CFStringRef display, CGSSpaceID id);`

I also tried a combination of `CGSHideSpaces()` and `CGSShowSpaces()`. Both approaches had the same result.

**Comment by koekeishiya** [comment] 2016-04-11 17:58
The people who created [TotalSpaces2](http://totalspaces.binaryage.com/) have achieved quite a lot it seems like. 

Due to [SIP causing problems] (http://blog.binaryage.com/on-el-capitan/), I would suspect a lot of what they do is achieved through code injection.

**Comment by cHoco** [comment] 2016-04-11 21:17
Yeah, they certainly did. I took a look at the Dock code, and it uses the same APIs, but obviously also updates its internal state and thats why it appears bugged when we just call the apis, cause it's not *listening* for changes. Unfortunately without injecting into the Dock I don't think we can do anything. I maybe thought we could try and modify com.apple.spaces.plist in /Users/currentUser/Library/Preferences and try synchronise changes with CFPreferencesAppSynchronize but the Dock doesn't seem to notice the preferences changes.

**Comment by mmmulani** [comment] 2016-04-11 22:17
sigh, you're both right. I did manage to do the weird thing of getting the spaces to change both visually and in windowserver with https://gist.github.com/mmmulani/7a47f33db62bb040e495e3f11e12b6bd but I wasn't able to sent an event for Dock to update it's internal state.

there might be something related to how it handles extra displays being added though, I haven't looked to find it's handler for that

**Comment by koekeishiya** [comment] 2016-04-12 11:30
>  Unfortunately without injecting into the Dock I don't think we can do anything.

I will probably look into this in the future. There are a lot of pretty useful stuff we would be able to do if so, such as being able to set the alpha value of any window. Change their window level - all "floating" windows could be changed to top-most, and so on.

**Comment by koekeishiya** [comment] 2016-04-12 21:00
Just to clarify, if this is something that I do end up looking into, it will probably be released in a separate version such that people who do not particularly care about these features do not have to disable `SIP` for no reason.

**Comment by mmmulani** [comment] 2016-04-13 23:19
@cHoco it seems that Dock.app will synchronize it's prefs if you send a notification like so:

```
NSDistributedNotificationCenter *center = [NSDistributedNotificationCenter defaultCenter];
[center postNotificationName:@"AppleShowScrollBarsSettingChanged" object:nil userInfo:nil deliverImmediately:YES];
```

**Comment by koekeishiya** [comment] 2016-04-14 15:06
Doubt much of this is relevant now: [paper written by developr of totalspaces1](https://reverse.put.as/wp-content/uploads/2011/06/How_to_re-engineer_OSX_to_behave_the_way_you_want_codebits_2012.pdf)

**Comment by cHoco** [comment] 2016-04-14 16:26
@mmmulani That syncs the preferences but unfortunately doesn't update the status of spaces, because it doesn't reload them. 

@koekeishiya the specify APIs mentioned don't work anymore and the notification mentioned for switching spaces isn't mentioned in the current Dock binary, so I think that was also removed. The other technical details are mostly still valid, the only problem is that SIP prevents a good chunk of the old methods used for code injection from working

**Comment by mmmulani** [comment] 2016-04-14 16:29
@cHoco yeah :cry: still looking out for some other approaches.

do you guys know if there's an radar open for this? will definitely bug them at WWDC

**Comment by koekeishiya** [comment] 2016-04-14 17:30
I've added an `kwmc space -fExperimental left | right | id` for users who want this. I do not have the function kill the dock to have it force update.

I figured that as I personally mostly use keyboard shortcuts, it did not matter that much to me.
Using the following binds works just fine for my behaviour, and maybe it is sufficient for other people too.
```
kwmc bind ctrl-1 space -fExperimental 1
kwmc bind ctrl-2 space -fExperimental 2
kwmc bind ctrl-3 space -fExperimental 3
kwmc bind ctrl-4 space -fExperimental 4
kwmc bind ctrl-5 space -fExperimental 5
kwmc bind ctrl-6 space -fExperimental 6
```

**Comment by cHoco** [comment] 2016-04-14 17:44
👍 

I still think code injection could be a nice addition, what would be the *prefered* method?
As far as I know on El Capitan, if we want to let the user keep SIP enabled there are only 2 ways:

1. Use *ScriptingAdditions*, this requires user to temporary disable SIP, install the .osax and then reenable SIP.
2. patch Dock executable by adding a LOAD_COMMAND to load a dylib when the executable is started, this doesn't require user to disable SIP, but modifies a system file (need to make a backup) and could obviously break if Dock executable is updated after an OS X update.

**Comment by koekeishiya** [comment] 2016-04-14 18:07
ScriptingAdditions sounds like the more sane option to perform in my opinion.

**Comment by dvcrn** [comment] 2016-04-20 02:56
Apologies for hijacking this issue but I noticed a small bug related to this. When jumping between spaces (for example with TotalSpaces that you mentioned earlier) I have it that kwm re-arranges all my windows. What usually happens is that it collapses all windows on both of my displays into 1 and reacts as if I just executed kwm for the first time. 

Is this something I can help debug and fix? My entire workflow is centered around spaces. 

Is using the experimental config above getting around this problem?

**Comment by koekeishiya** [comment] 2016-04-21 12:15
> What usually happens is that it collapses all windows on both of my displays into 1 and reacts as if I just executed kwm for the first time. 

This will probably happens if you use TotalSpaces with all space-transition-animations disabled.
This is because the transition happens so fast, that the API Kwm would use to check if a space transition is in progress, is not updated fast enough.

When Kwm itself is the one performing the space-transition (`kwmc space -fExperimental ..`) I can just special case this such that the above issue does not happen.

**Comment by dvcrn** [comment] 2016-04-21 12:38
> This will probably happens if you use TotalSpaces with all space-transition-animations disabled.

That is correct and exactly what I am using. I will try the experimental transition then.

**Comment by mickaelperrin** [comment] 2016-04-27 16:08
This feature is absolutely incredible. As a (lot of) spaces user, my computer seems to be a lot more reactive and my workflow a lot more fluid ! Thanks !

I encounter a silly bug since yesterday (when I activated this feature with keybindings) but I am not sure if it is related to kwm. However, regarding the information related to the Dock, I presume it could be linked.

So, after some amount of time of using the feature, the menu bar displays the menu of Finder and no more the menu of the application. Restarting kwm didn't help, but closing application does. It seems that the closing of one application resolves the problem (most of time it's Google Chrome, but last time it was my IDE PHPStorm).

Any ideas if kwm could be at the origin of this problem ? Or ways to provide a much helpful feedback ?

**Comment by mickaelperrin** [comment] 2016-06-19 17:08
As with kwm 3.0.0 focus is now managed by OSX, should it be possible to emulate a mouse click at the current mouse position after invoking a space change ? This would help a lot to navigate through spaces without having to click each time to get an app in the space focused.

**Comment by koekeishiya** [comment] 2016-06-19 17:27
> As with kwm 3.0.0 focus is now managed by OSX, should it be possible to emulate a mouse click at the current mouse position after invoking a space change ? This would help a lot to navigate through spaces without having to click each time to get an app in the space focused.

I've made a special case for experimental space transition. See that specific issue for detail.

**Comment by mickaelperrin** [comment] 2016-06-19 20:58
Just gave a try to this new patch, and I can confirm that works great so far. Thanks so much, this feature is so useful !

**Closed** 2016-08-04 10:41 UTC
Labels: code-injection, experimental
