### ISSUE TITLE
Red dot in upper left hand corner when viewing full screen videos

### ISSUE THREAD

**Issue by ericgroom** [koekeishiya/kwm#267] opened 2016-03-27 05:34 UTC
When watching a video in fullscreen, a small red dot will be shown in the upper left hand corner. I tested this in Firefox with both YouTube and twitch.tv. I am unable to test in safari due to a bug in El Capitan that freezes my computer (unrelated). I included photos of a video playing with kwm running and without it running. It would be great if someone could test this in chrome also. 
![running](https://cloud.githubusercontent.com/assets/16406453/14063988/d2f3aaca-f3a2-11e5-826f-865eb8e0fb83.png)
![not running](https://cloud.githubusercontent.com/assets/16406453/14063989/d468eb5e-f3a2-11e5-966c-d449ef9a91f7.png)

**Comment by koekeishiya** [comment] 2016-03-27 10:18
I do not have this problem, but it is caused by the focused border. Disabling it during fullscreen should do the trick for now.

**Comment by koekeishiya** [comment] 2016-04-07 19:52
Should be fixed in the latest commit.

**Closed by koekeishiya** 2016-04-07 19:52 UTC
Labels: bug
