### ISSUE TITLE
Autoraise not working after minimizing windows

### ISSUE THREAD

**Issue by LGUG2Z** [koekeishiya/kwm#393] opened 2016-06-19 21:24 UTC
Thanks to the post on [syntax translation](https://github.com/koekeishiya/kwm/issues/386) and the [3.0 config reference](https://koekeishiya.github.io/kwm/kwmc.html) the move to this new version has largely been quite painless.

One problem that I have run in to however, is that when I minimize a window (cmd+m) in tiling mode (bsp), I'm no longer able to autoraise any of the remaining windows with the cursor, nor give them focus using the kwmc window -f command.

On the other hand, if I try to hide an application's windows (cmd+h), I am able to autoraise and switch focus among the remaining windows with the kwmc window -f command, but the remaining windows do not resize to fill the screen and there is a gap where the now hidden window was (similar to the behaviour mentioned in #392), and it is not possible to use any of the kwm commands to swap or move a marked window into the gap that is left by the hidden window.

These are what I believe are the settings that might be relevant to this behaviour from my kwmrc.

kwmc config tiling bsp
kwmc config float-non-resizable on
kwmc config lock-to-container on
kwmc config focus-follows-mouse on
kwmc config standby-on-float on
kwmc config mouse-follows-focus on
kwmc config cycle-focus on

**Comment by koekeishiya** [comment] 2016-06-20 00:33
> One problem that I have run in to however, is that when I minimize a window (cmd+m) in tiling mode (bsp), I'm no longer able to autoraise any of the remaining windows with the cursor

Definitely a bug.

> nor give them focus using the kwmc window -f command.

This is intended. If OSX doesn't assign focus to a window that is eligible for the `window -f`command, this is the expected behaviour.

> On the other hand, if I try to hide an application's windows (cmd+h)

Hiding applications is not supported.

**Comment by LGUG2Z** [comment] 2016-06-20 07:02
A bit more info on how to reproduce this after playing around with it a bit this morning: 

It seems that the minimise bug only happens when I am minimising the last visible window of an application. So If I have 2 iTerm windows open and one Firefox window open, minimising one of the iTerm windows will pass the focus to the other iTerm window that is still on screen, but if I close the Firefox window, the focus will stay locked on Firefox and I won't be able to give focus to either of the iTerm windows without clicking on them directly.

**Comment by koekeishiya** [comment] 2016-06-20 12:45
Fixed on master.

**Closed by koekeishiya** 2016-06-20 12:45 UTC
