### ISSUE TITLE
Does not focus chrome extension's dialog

### ISSUE THREAD

**Issue by maksimr** [koekeishiya/kwm#232] opened 2016-03-13 20:03 UTC
Is it possible does not focus chrome extension's dialog window?

http://screencast.com/t/qMZXgrvi

**Comment by koekeishiya** [comment] 2016-03-13 23:04
This would require you to edit the source code and have Kwm ignore the window by name.

**Comment by cHoco** [comment] 2016-03-15 16:11
@koekeishiya I was trying to fix this issue because various popups get focused even though they're not proper windows. I found out that that these UI element that get focus can be distinguished from the other windows because they have a AXWindow attribute (usually set to nil) so we should filter windows based on that:

``` cpp
    AXUIElementRef WindowRef;
    AXUIElementRef hasWindow = NULL;
    if(GetWindowRef(Window, &WindowRef)) {
        AXError Error = AXUIElementCopyAttributeValue(WindowRef, kAXWindowAttribute, (CFTypeRef*)&hasWindow);
        if (Error == kAXErrorSuccess || Error == kAXErrorNoValue) {
            return false; //NOT A PROPER WINDOW
        }
    }
```

I tested it by adding this logic the ShouldWindowGainFocus and it works, but I was thinking that since these are not proper windows and CGWindowListCopyWindowInfo doesn't seem to keep up when they are destroyed, should we just filter them out from the KWMTiling.WindowLst and KWMTiling.FocusLst?

**Comment by chrishoage** [comment] 2016-03-15 17:17
I wonder if that would fix the Sublime Text 3 auto-complete window from closing when the mouse hovers over it giving it focus.

**Comment by cHoco** [comment] 2016-03-15 17:49
I just tried and it seems to fix it!

**Comment by chrishoage** [comment] 2016-03-15 18:14
I added the code to `ShouldWindowGainFocus` and it does not appear to keep the auto-complete window from closing when the mouse hovers over it. 

It does however keep the chrome extension windows from closing when they happen to span across another window which before would trigger autoraise. So to me this is a huge improvement.

I wonder if an approach like this could be used to fix all the other little autoraise issues like with Launch pad or Dock Stacks?

**Comment by koekeishiya** [comment] 2016-03-15 18:20
> I was trying to fix this issue because various popups get focused even though they're not proper windows. I found out that that these UI element that get focus can be distinguished from the other windows because they have a AXWindow attribute (usually set to nil) so we should filter windows based on that:

I was under the impression I already did this. Check FilterWindowList():window.cpp and GetWindowRole():window.cpp

**Comment by cHoco** [comment] 2016-03-15 18:28
@chrishoage I added that code to the filtering functions so that's probably why the popup still closes, I'll clean up the code and upload a diff for you to try.

@koekeishiya In UpdateWindowTree() you update the WindowsLst assign it to FocusLst and then filter it. So if I undestand correctly only WindowLst get filtered (and that makes sense since we probably want to filter from tiling some windows but not from focusing) But this type of windows, since they aren't window should be filtered in both lists.

**Comment by koekeishiya** [comment] 2016-03-15 18:31
> In UpdateWindowTree() you update the WindowsLst assign it to FocusLst and then filter it. So if I undestand correctly only WindowLst get filtered (and that makes sense since we probably want to filter from tiling some windows but not from focusing) But this type of windows, since they aren't window should be filtered in both lists.

Right, makes sense. Cheers.

**Comment by koekeishiya** [comment] 2016-03-15 19:07
Has anyone found anything that breaks because of this change? `popclip` and so on?
I don't use any of these applications, so I wouldn't know.

**Comment by dominiklohmann** [comment] 2016-03-15 19:47
Little Snitch still works, maybe @matthewdias can confirm it for popclip? He did that the last time we had that question as well.

**Comment by chrishoage** [comment] 2016-03-15 20:27
@cHoco ping me when you have that diff, I'm curious to try it and see how many of the autoraise issues I have

**Comment by koekeishiya** [comment] 2016-03-15 20:41
I have no idea how I have been overlooking this for so long. All we really have to do is make sure the same `GetWindowRole()` check I perform in the `FilterWindowList..` functions also apply to the FocusLst.

**Comment by cHoco** [comment] 2016-03-15 20:48
@chrishoage Right now I was applying whole filtering function to all https://gist.github.com/cHoco/4070853127a876b4ab02

**Comment by koekeishiya** [comment] 2016-03-15 20:48
Try the following patch and let me know if it improves or breaks anything:
https://gist.github.com/koekeishiya/24290b5154b66ed0e972

**Comment by cHoco** [comment] 2016-03-15 21:08
@koekeishiya Maybe also allow `kAXMenuRole` as an allowed Role in `FocusWindowBelowCursor` ?

**Comment by chrishoage** [comment] 2016-03-15 21:09
I have applied both of those patches independently from each other and both of them fix the Sublime Text Auto Complete issue! 

Unfortunately any chrome extension that opens across another window is unusable, as it tirggers autorise on the window behind it. 

Not sure what the difference is between the two approaches in the diffs but they each seemed to work. 

As a curiosity I tried to apply both of them at the same time and they didn't seem to cause any issues with a few minutes of testing, and the ST3 auto-complete widnowissue have been solved.

**Comment by koekeishiya** [comment] 2016-03-15 21:12
> Unfortunately any chrome extension that opens across another window is unusable, as it tirggers autorise on the window behind it.

That's the problem by simply ignoring the window. We need to detect that the window is there, and stop the focus-follows-mouse from being applied, instead of just "ignoring" the window.

**Comment by cHoco** [comment] 2016-03-15 21:22
Yeah, I just applied the filter for allowing quick testing for @chrishoage while I actually was using your exact same  approach in my local branch.

**Comment by chrishoage** [comment] 2016-03-15 21:35
@cHoco correct, the chrome issue persists with just the @koekeishiya patch applied. Both fix the Sublime Text Issue. Neither fixed the Chrome Ext issue.

**Comment by koekeishiya** [comment] 2016-03-15 21:46
I believe the `ShouldWindowGainFocus()` function may be redundant now that we check the AXWindowRoleAttribute

**Comment by cHoco** [comment] 2016-03-15 22:01
I think that Chrome issue happens when in the FocusWindowBelowCursor a good window for focus is analysed before the current window and these pseudo windows that we are filtering. Maybe we can fix it by keep on iterating the FocusLst to check that there aren't other windows, or just iterate the other way around? (not sure if there is any logic in the window order `CGWindowListCopyWindowInfo` gives

**Comment by koekeishiya** [comment] 2016-03-15 22:03
> I think that Chrome issue happens when in the FocusWindowBelowCursor a good window for focus is analysed before the current window and these pseudo windows that we are filtering. Maybe we can fix it by keep on iterating the FocusLst to check that there aren't other windows, or just iterate the other way around? (not sure if there is any logic in the window order CGWindowListCopyWindowInfo gives

The window list is already sorted by z-axis, which is why focus-follows-mouse can be implemented "this easy". It does all the sorting for us. The earlier in our list the window is, the more "frontmost" it is.

**Comment by chrishoage** [comment] 2016-03-15 22:14
@koekeishiya that actually did work! 

```diff
diff --git a/kwm/window.cpp b/kwm/window.cpp
index 408ecc8..b503f20 100644
--- a/kwm/window.cpp
+++ b/kwm/window.cpp
@@ -253,18 +253,20 @@ bool FocusWindowOfOSX()
 
 bool ShouldWindowGainFocus(window_info *Window)
 {
-    return Window->Layer == CGWindowLevelForKey(kCGNormalWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGFloatingWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGTornOffMenuWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGDockWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGMainMenuWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGMaximumWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGModalPanelWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGUtilityWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGOverlayWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGHelpWindowLevelKey) ||
-           Window->Layer == CGWindowLevelForKey(kCGPopUpMenuWindowLevelKey) ||
-           Window->Layer == 1490; // Note(koekeishiya): Unknown WindowLevelKey constant
+    bool Result =  Window->Layer == CGWindowLevelForKey(kCGNormalWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGFloatingWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGTornOffMenuWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGDockWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGMainMenuWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGMaximumWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGModalPanelWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGUtilityWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGOverlayWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGHelpWindowLevelKey) ||
+                   Window->Layer == CGWindowLevelForKey(kCGPopUpMenuWindowLevelKey) ||
+                   Window->Layer == 1490; // Note(koekeishiya): Unknown WindowLevelKey constant
+
+    return Result;
 }
 
 void FocusWindowBelowCursor()
@@ -290,14 +292,20 @@ void FocusWindowBelowCursor()
            KWMTiling.FocusLst[WindowIndex].Y == 0)
             continue;
 
-        if(IsWindowBelowCursor(&KWMTiling.FocusLst[WindowIndex]) &&
-           ShouldWindowGainFocus(&KWMTiling.FocusLst[WindowIndex]))
+        if(IsWindowBelowCursor(&KWMTiling.FocusLst[WindowIndex]))
         {
-           if(WindowsAreEqual(KWMFocus.Window, &KWMTiling.FocusLst[WindowIndex]))
-               KWMFocus.Cache = KWMTiling.FocusLst[WindowIndex];
-           else
-               SetWindowFocus(&KWMTiling.FocusLst[WindowIndex]);
-
+            CFTypeRef Role, SubRole;
+            if(GetWindowRole(&KWMTiling.FocusLst[WindowIndex], &Role, &SubRole))
+            {
+                if((CFEqual(Role, kAXWindowRole) && CFEqual(SubRole, kAXStandardWindowSubrole)) ||
+                   IsAppSpecificWindowRole(&KWMTiling.FocusLst[WindowIndex], Role, SubRole))
+                {
+                    if(WindowsAreEqual(KWMFocus.Window, &KWMTiling.FocusLst[WindowIndex]))
+                        KWMFocus.Cache = KWMTiling.FocusLst[WindowIndex];
+                    else
+                        SetWindowFocus(&KWMTiling.FocusLst[WindowIndex]);
+                }
+            }
             return;
         }
     }
```

is the state my git repo is in now

**Comment by koekeishiya** [comment] 2016-03-15 22:17
The only question now is, does this break `Little Snitch` @dominiklohmann ?
I've confirmed that `popclip` does work with these changes.

**Comment by dominiklohmann** [comment] 2016-03-15 22:27
It kinda does. It gets focused and does not lose focus, but cannot gain focus from focus-follows-mouse anymore. I'm fine with that, since I can control it with keyboard shortcuts as long as it gains focus when it pops up.

**Comment by koekeishiya** [comment] 2016-03-15 22:31
> It kinda does. It gets focused and does not lose focus automatically like before the layer 1490 patch, but cannot gain focus from focus-follows-mouse anymore.

The above changes requires `kwmc config focus standby-on-float off` to work properly. Having that option on will cause weird issue. Forgot to mention that.

**Comment by dominiklohmann** [comment] 2016-03-15 22:36
I'm getting the same behaviour with standby-on-float set to off, Little Snitch is not considered a floating window by kwm.

Using kwm without standby-on-float can be really annoying at times.

**Comment by koekeishiya** [comment] 2016-03-15 22:39
> The above changes requires kwmc config focus standby-on-float off to work properly. Having that option on will cause weird issue. Forgot to mention that.

Nvm what I said here, this was the result of some other change I have made locally.

**Comment by dominiklohmann** [comment] 2016-03-15 22:40
Okay, then I'm all for merging this into master as it seems to work just fine.

**Comment by koekeishiya** [comment] 2016-03-15 23:04
I'm gonna go ahead and merge the changes I've made as they appear to be an improvement.

**Closed** 2016-03-15 23:05 UTC

**Comment by cHoco** [comment] 2016-03-15 23:45
Great work :+1:

**Comment by chrishoage** [comment] 2016-06-20 21:05
Chrome Extension Auto Raise issues has regressed with 3.0.0

**Comment by koekeishiya** [comment] 2016-06-20 21:15
> Chrome Extension Auto Raise issues has regressed with 3.0.0 

Focus follows mouse performs the exact same filtering as before. Do you have any rules that could potentially do something here?

**Comment by chrishoage** [comment] 2016-06-20 21:17
This is an issue with auto-raise. 

I have a chrome extension that spills off the edge of the window. With the code in this ticket, when I opened the extension opened over an adjacent window autoraise did not trigger the window behind the chrome extension, now it does. 

_Something_ changed, because now I can't use the chrome extension with autorise enabled. (Extension in my case is 1Password, which totally worked with the code in this ticket)

**Comment by koekeishiya** [comment] 2016-06-20 21:22
If i read this issue correctly, the following was the old code that fixed it:
```
 if((CFEqual(Role, kAXWindowRole) && CFEqual(SubRole, kAXStandardWindowSubrole)) ||
    IsAppSpecificWindowRole(&KWMTiling.FocusLst[WindowIndex], Role, SubRole))
```

This is the code version 3.0.0 has:
```
 if((AXLibIsWindowStandard(Window) ||
    (AXLibIsWindowCustom(Window))))

Function implementations:
 35 bool AXLibIsWindowStandard(ax_window *Window)
 36 {                       
 37     bool Result = ((CFEqual(Window->Type.Role, kAXWindowRole)) &&
 38                            (CFEqual(Window->Type.Subrole, kAXStandardWindowSubrole)));
 39     return Result;
 40 }           
 41         
 42 bool AXLibIsWindowCustom(ax_window *Window)
 43 {       
 44     bool Result = ((Window->Type.CustomRole) &&
 45                           ((CFEqual(Window->Type.Role, Window->Type.CustomRole)) ||
 46                            (CFEqual(Window->Type.Subrole, Window->Type.CustomRole))));
 47     return Result;
 48 }
```

**Comment by chrishoage** [comment] 2016-06-20 21:30
I tried making a screen recording of the issue, but when quick time was recording I couldn't even hover over the extension dialog window, it would close immediately. I can share the video if you want, but it is not an accurate representation of the issue. I can use the extension while the mouse is over chrome, but once the mouse leaves the chrome window, the extension dialog closes, because the window behind the extension is focused.

**Comment by koekeishiya** [comment] 2016-06-20 21:38
I wonder if the problem could be as simple as Chrome not creating a `kAXWindowCreated` notification, which is why the window appers nonexistant to Kwm.

**Comment by chrishoage** [comment] 2016-06-20 21:39
That sounds like a really good guess.

**Comment by koekeishiya** [comment] 2016-06-20 21:47
Try this patch and see if that fixes it.

https://gist.github.com/koekeishiya/8483f6e3001d70dafc08f15a6bd25712

**Comment by chrishoage** [comment] 2016-06-20 22:01
I can't seem to apply that patch. I keep getting `fatal: corrupt patch at line 23`

**Comment by koekeishiya** [comment] 2016-06-20 22:03
Uh my bad, try this one: https://gist.github.com/koekeishiya/655f1bc3707344372c5711299b421995

**Comment by chrishoage** [comment] 2016-06-20 22:06
Negative, the chrome extension still seems to be "invisible" to kwm. When I hover over a window behind the chrome extension, the chrome extension closes.

**Comment by koekeishiya** [comment] 2016-06-20 22:23
Hmm, I really have no idea at this point, considering that last patch did nothing..
