### ISSUE TITLE
Emacs (spacemacs) crashes kwm

### ISSUE THREAD

**Issue by AhmedAA** [koekeishiya/kwm#40] opened 2016-01-04 16:28 UTC
Container spawns without any regards to kwm, when spawning emacs (with a spacemacs configuration). It's as if kwm never registers the window/container, and any attempt at using hotkeys only works on other windows behind the emacs window.

When trying to use the hotkeys on a desktop where there are no other windows than emacs, kwm simply crashes.

I am not sure if it is a problem with emacs not being spawned correctly, or kwm not registering the window. I can try to change the size of the emacs window/making it spawn in freeform or something and see if that helps.

**Comment by koekeishiya** [comment] 2016-01-04 17:43
Will look into it a some point when I have time.
For the time being, you can set it to always float in .kwmrc so that it will not cause Kwm to segfault and ruin the other workspaces.

Something along the lines of `kwmc config float Spacemacs` I would assume

**Comment by koekeishiya** [comment] 2016-01-04 17:59
So I just installed Spacemacs and it seems to work just fine for me.
Do you happen to have the titlebar removed? If so that is most likely the issue, as I had to make a special case for iTerm2 without titlebar.

**Comment by AhmedAA** [comment] 2016-01-04 18:01
No, I haven't removed the titlebar, but I have configured it to remove all the entires in the menubar at the top. I'll try to look at it, it just seems weird..

**Comment by koekeishiya** [comment] 2016-01-04 18:11
So much settings available for spacemacs that it would take me ages to try and reproduce this, however, what Kwm does is use the accessibility role AXWindow, and it has a sub-role of AXStandardWindow, to track windows that should be tiled.

Title-less windows usually have their role set to AXDialog (iTerm2 does this) and needs to be handled separately.

What you can do is run the "Accessibility Inspector" tool shipped with OSX, to see a lot of this information. Maybe this could help you identify why your modified config breaks Kwm.

**Comment by AhmedAA** [comment] 2016-01-04 18:31
Placing a dump here, not entirely sure what exactly to look for..
What I do notice is that it seems to have the roles you are mentioning

    AXApplication
        AXTextField:AXStandardWindow
Attributes
    isAccessibilityFocused	YES
    accessibilityTitle	*spacemacs*
    accessibilityGrowArea	<nil>
    accessibilityMinimizeButton	<AXButton:AXMinimizeButton>
    accessibilityDocument	<nil>
    accessibilityCloseButton	<AXButton:AXCloseButton>
    isAccessibilityMain (W)	YES
    accessibilityFullScreenButton	<AXButton:AXFullScreenButton>
    accessibilityProxy	<nil>
    accessibilityDefaultButton	<nil>
    isAccessibilityMinimized (W)	NO
    accessibilityChildren	4 items
    accessibilityRole	AXTextField
    accessibilityParent	<AXApplication>
    accessibilityTitleUIElement	<AXStaticText>
    accessibilityCancelButton	<nil>
    isAccessibilityModal	NO
    accessibilitySubrole	AXStandardWindow
    accessibilityZoomButton	<AXButton:AXFullScreenButton>
    accessibilityRoleDescription	text field
    accessibilityToolbarButton	<nil>
    accessibilityFrame	x=-0.00 y=23.00 w=837.00 h=1020.00
Actions
    accessibilityPerformRaise

**Comment by koekeishiya** [comment] 2016-01-04 18:39
Ok so I think I've found the issue then.
Mine looks like this: 

    AXApplication
         AXWindow:AXStandardWindow

So basically, the AXStandardWindow sub-role is never checked, if the "main role" is not AXWindow.
It appears from your output that even tho the sub-role is indeed AXStandardWindow, the "main role" does not fit the requirements.

I'll look into a way for users to simply create rules for allowing specific applications to be tiled regardless of this role-mismatch

**Comment by AhmedAA** [comment] 2016-01-04 18:40
A snippet in the example kwmrc would do nicely, I think :)
I have no idea how to write the rule atm, but then again, I am doing other stuff right now than looking into the customising.

**Comment by koekeishiya** [comment] 2016-01-04 18:43
Currently you would have to edit the FilterWindowList function inside kwm/window.cpp and recompile.
I'll probably have this fixed with a system for future similar bugs that allow users to simply fix it using the config file.

**Comment by AhmedAA** [comment] 2016-01-04 18:44
Then I'll simply wait.
I do have your repo open in a tab anyways, so I am aware of updates hehe :)

Thanks!

**Comment by koekeishiya** [comment] 2016-01-04 19:13
Think i got a working system for this now, if you'd like to test

**Comment by AhmedAA** [comment] 2016-01-04 19:20
Sure, point me to the branch

**Comment by koekeishiya** [comment] 2016-01-04 19:27
It seems stable enough, so it's on the current master branch.
So basically it works this way:

Find the name of your application that misbehaves (I use my 'nerdTool' bar that runs scripts to display this on the top-left corner running kwmc focused).
After you know the name of the application, open Accessibility Inspector and identify the role of the window. In your case that would be AXTextField, or AXStandardWindow.

While Kwm is running, you can do `kwmc config add-role application role` to allow Kwm to tile that type of windows for that single. This can also be added directly to your .kwmrc config

For this specific example, if you do `kwmc config add-role Emacs AXStandardWindow` the issue should be fixed.

**Comment by AhmedAA** [comment] 2016-01-04 19:31
And it works!

Awesome, thanks!

**Comment by koekeishiya** [comment] 2016-01-04 19:34
Glad we were able to work out this issue, thanks.
I'll reference this issue from the readme for explanation of how the custom roles work.

**Comment by AhmedAA** [comment] 2016-01-04 19:39
Mmm, it seems like I am still segfaulting it after fiddling a little around with some keys. Dunno if this is related to the fix.

After trying again without emacs running, it still does it. It segfaults just by opening a few windows, and cycling through the windows or tiling modes.

**Comment by koekeishiya** [comment] 2016-01-04 19:40
Uh, ok wait let me do some more testing. Maybe I broke something.

**Comment by AhmedAA** [comment] 2016-01-04 19:47
That's just plain weird then..
I guess it is just my setup then.

**Comment by koekeishiya** [comment] 2016-01-04 19:49
The segfault issues you are having could be happening because some of your binds perform a faulty kwmc command. I do not validate kwmc commands yet in kwm/interpreter.cpp and so a mistaken syntax (a typo or anything), could be the culprit.

Only thing I can suggest is going through your binds again.

**Comment by AhmedAA** [comment] 2016-01-04 19:50
I haven't changed them at all, I am using stock binds o_o

**Comment by koekeishiya** [comment] 2016-01-04 19:52
Try to manually copy all the bind parts from the examples config, I did fix a mistake in there earlier.
I don't really have any other ideas of what could be causing it.

**Comment by AhmedAA** [comment] 2016-01-04 19:55
Well, it helps to know that it crashes when pushing a key that doesn't exist.
I am still learning the keybinds, so I am pressing wrong a couple of times. Just my own fault then :) Now that I am actually making sure I am pressing correctly, it seems to be stable!

**Comment by koekeishiya** [comment] 2016-01-04 19:59
Aight sounds good, I'll mark this issue as closed again.

**Closed by koekeishiya** 2016-01-04 19:59 UTC
Labels: bug

**Comment by dongcarl** [comment] 2016-03-06 21:16
@koekeishiya I'm not sure why but kwm is still not working with Spacemacs after doing `kwmc config add-role AXStandardWindow Emacs`... Here's my full config: http://pastebin.com/T9HHHn5J

**Comment by dongcarl** [comment] 2016-03-07 08:18
@AhmedAA Nothing else controlling window placement... No window size specified :-(

**Comment by koekeishiya** [comment] 2016-03-07 12:15
how about `kwmc config add-role AXWindow Emacs` ?

> Right click the .app folder and click "show package contents".
Open the Info.plist file and locate the string "Bundle Name". The value of this field is the name to pass to Kwm.

Also make sure the name is actually Emacs

**Comment by AhmedAA** [comment] 2016-03-07 12:34
For comparison, it is called `CFBundleName` here, and it is set to `Emacs`.
Also, I installed Emacs from http://emacsformacosx.com/ and not from brew.
My version is 24.5.

Can you @dongcarl confirm your setup? :)

**Comment by koekeishiya** [comment] 2016-03-07 12:45
I have emacs installed through brew (24.5.1) and spacemacs 0.105.0.

Default settings on both as I do not use emacs, and it works straight out of the box without having to tell Kwm anything.

I really have no clue other than what has been covered already in this issue.

**Comment by dongcarl** [comment] 2016-03-11 18:04
@AhmedAA @koekeishiya I installed`emacs-mac-port` per spacemacs' instructions here: https://github.com/syl20bnr/spacemacs#os-x I checked in the `Info.plist` and there isn't a `CFBundleName`! How strange!

**Comment by dvcrn** [comment] 2016-10-04 05:46
Hi! Chiming in that I am having similar problems. I recently switched from the railwaycat version of emacs to the normal brewed one. 

Adding
```
kwmc config add-role AXWindow Emacs
kwmc rule owner="Emacs" properties={role="AXStandardWindow"}
```

forces the window to tile but follow focus for all other windows breaks. (only this combination worked. Adding only one didn't do anything)

**Comment by webavant** [comment] 2016-11-21 17:00
Confirming that this addition to `kwmrc` works for the `emacs-pretest` package in `homebrew`. Also confirming that restarting `kwm` after making this modification to the config file introduces the appearance reported `focus-follows-mouse` bug for me.

**Comment by webavant** [comment] 2016-11-21 17:06
I tested again and now I'm wondering if I am mistaken. Reverting to the example config, `focus-follows-mouse` is still not working for some reason, although I now realize I should have reported this in #521 or in another issue. I will not expect a response or re-open the issue since I don't use this feature (or a mouse for that matter) and it appears the bug has already been reported. Great software, thanks!
